/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIBuscarEntidad.java
 *
 * Created on 21/07/2012, 12:20:32 PM
 */
package Vista;

import Controlador.ControlConvenio_entidad;
import Controlador.ControlEntidad;
import Estructural.Convenio_entidad;
import Estructural.Entidad_convenio;
import Modelo.IServicioConvenios;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kmilo
 */
public class GUIBuscarEntidad extends javax.swing.JFrame {
  
  private IServicioConvenios servicioConvenios;
  private ControlEntidad controlEntidad;
  private ControlConvenio_entidad controlConvenio_entidad;
  private int numeroConvenio;

  /** Creates new form GUIBuscarEntidad */
  public GUIBuscarEntidad(IServicioConvenios servicioConvenios, int numeroConvenio) throws RemoteException {
    initComponents();
    this.servicioConvenios = servicioConvenios;
    this.numeroConvenio = numeroConvenio;
    controlEntidad = new ControlEntidad(servicioConvenios);
    controlConvenio_entidad = new ControlConvenio_entidad(servicioConvenios);
    deshabilitarCampos();
    this.setLocationRelativeTo(null);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosBusquedEntidad = new javax.swing.JPanel();
        lblLogoBusquedaEntidad = new javax.swing.JLabel();
        lblTituloBusquedaEntidad = new javax.swing.JLabel();
        panelDatosBusqueda = new javax.swing.JPanel();
        btn_buscar_entidad = new javax.swing.JButton();
        lblNitBusqueda = new javax.swing.JLabel();
        txt_Nit_Buscar = new javax.swing.JTextField();
        panelResultadoBusqueda = new javax.swing.JPanel();
        lblNit = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        panelDescBusqueda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblNitResultado = new javax.swing.JLabel();
        lblNombreResultado = new javax.swing.JLabel();
        btnAgregar_al_convenio = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        barraMenuBusquedaEntidad = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Entidad");

        panelDatosBusquedEntidad.setBackground(new java.awt.Color(255, 255, 255));

        lblLogoBusquedaEntidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entidad.png"))); // NOI18N

        lblTituloBusquedaEntidad.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        lblTituloBusquedaEntidad.setText("Busqueda de Entidades");

        panelDatosBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

        btn_buscar_entidad.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
        btn_buscar_entidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarConvenio.png"))); // NOI18N
        btn_buscar_entidad.setText("Buscar");
        btn_buscar_entidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_entidadActionPerformed(evt);
            }
        });

        lblNitBusqueda.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        lblNitBusqueda.setText("NIT de la Entidad");

        txt_Nit_Buscar.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N

        javax.swing.GroupLayout panelDatosBusquedaLayout = new javax.swing.GroupLayout(panelDatosBusqueda);
        panelDatosBusqueda.setLayout(panelDatosBusquedaLayout);
        panelDatosBusquedaLayout.setHorizontalGroup(
            panelDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosBusquedaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblNitBusqueda)
                .addGap(18, 18, 18)
                .addComponent(txt_Nit_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_entidad)
                .addGap(77, 77, 77))
        );
        panelDatosBusquedaLayout.setVerticalGroup(
            panelDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar_entidad)
                    .addComponent(lblNitBusqueda)
                    .addComponent(txt_Nit_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelResultadoBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panelResultadoBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados de la busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

        lblNit.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        lblNit.setText("NIT");

        lblNombre.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        lblNombre.setText("Nombre");

        panelDescBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panelDescBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        txtDescripcion.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout panelDescBusquedaLayout = new javax.swing.GroupLayout(panelDescBusqueda);
        panelDescBusqueda.setLayout(panelDescBusquedaLayout);
        panelDescBusquedaLayout.setHorizontalGroup(
            panelDescBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDescBusquedaLayout.setVerticalGroup(
            panelDescBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblNitResultado.setText("Texto del NIT");

        lblNombreResultado.setText("Texto Nombre");

        javax.swing.GroupLayout panelResultadoBusquedaLayout = new javax.swing.GroupLayout(panelResultadoBusqueda);
        panelResultadoBusqueda.setLayout(panelResultadoBusquedaLayout);
        panelResultadoBusquedaLayout.setHorizontalGroup(
            panelResultadoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDescBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelResultadoBusquedaLayout.createSequentialGroup()
                        .addComponent(lblNit)
                        .addGap(37, 37, 37)
                        .addComponent(lblNitResultado)
                        .addGap(166, 166, 166)
                        .addComponent(lblNombre)
                        .addGap(38, 38, 38)
                        .addComponent(lblNombreResultado)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelResultadoBusquedaLayout.setVerticalGroup(
            panelResultadoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelResultadoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNit)
                    .addComponent(lblNombre)
                    .addComponent(lblNitResultado)
                    .addComponent(lblNombreResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDescBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAgregar_al_convenio.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
        btnAgregar_al_convenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        btnAgregar_al_convenio.setText("Agregar al convenio");
        btnAgregar_al_convenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_al_convenioActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosBusquedEntidadLayout = new javax.swing.GroupLayout(panelDatosBusquedEntidad);
        panelDatosBusquedEntidad.setLayout(panelDatosBusquedEntidadLayout);
        panelDatosBusquedEntidadLayout.setHorizontalGroup(
            panelDatosBusquedEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosBusquedEntidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosBusquedEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResultadoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatosBusquedEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelDatosBusquedEntidadLayout.createSequentialGroup()
                            .addComponent(lblTituloBusquedaEntidad)
                            .addGap(18, 18, 18)
                            .addComponent(lblLogoBusquedaEntidad))
                        .addComponent(panelDatosBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosBusquedEntidadLayout.createSequentialGroup()
                        .addComponent(btnAgregar_al_convenio)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        panelDatosBusquedEntidadLayout.setVerticalGroup(
            panelDatosBusquedEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosBusquedEntidadLayout.createSequentialGroup()
                .addGroup(panelDatosBusquedEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosBusquedEntidadLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblTituloBusquedaEntidad))
                    .addGroup(panelDatosBusquedEntidadLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblLogoBusquedaEntidad)))
                .addGap(18, 18, 18)
                .addComponent(panelDatosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelResultadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosBusquedEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar_al_convenio, 0, 0, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuArchivo.add(jMenuItem1);

        barraMenuBusquedaEntidad.add(menuArchivo);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
        menuAyuda.setText("Ayuda ?");
        menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        barraMenuBusquedaEntidad.add(menuAyuda);

        setJMenuBar(barraMenuBusquedaEntidad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosBusquedEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosBusquedEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_buscar_entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_entidadActionPerformed
// TODO add your handling code here:
  String NIT = "";
  boolean controlDatos = true;
  if (txt_Nit_Buscar.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Digitar un NIT para buscar una entidad", "Error en NIT", 0);
    controlDatos = false;
  } else {
    NIT = txt_Nit_Buscar.getText().trim();
  }
  if (controlDatos) {
    try {
      Entidad_convenio entidad = controlEntidad.ConsultaEntidad(NIT);
      if (entidad != null) {
        cargarDatos(entidad);
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se encontraron entidades con NIT suministrado", "No hay resultados", 2);
        deshabilitarCampos();
      }
    } catch (RemoteException ex) {
      Logger.getLogger(GUIBuscarEntidad.class.getName()).log(Level.SEVERE, null, ex);
    }
  }
}//GEN-LAST:event_btn_buscar_entidadActionPerformed
  
private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
  this.dispose();
}//GEN-LAST:event_jMenuItem1ActionPerformed
  
private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
  this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed
  
private void btnAgregar_al_convenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_al_convenioActionPerformed
// TODO add your handling code here:
  String NIT = lblNitResultado.getText().trim();
  int convenio = numeroConvenio;
  Convenio_entidad convenio_entidad = new Convenio_entidad(0, convenio, NIT);
  boolean controlRelacion = false;
  try {
    controlRelacion = controlConvenio_entidad.AdicionConvenio_entidad(convenio_entidad);
    if (controlRelacion) {
      JOptionPane.showMessageDialog(rootPane, "Se ha añadido la entidad buscada al convenio numero: " + numeroConvenio, "Relacion creada", 1);
      limpiarFormulario();
    } else {
      JOptionPane.showMessageDialog(rootPane, "No se pudo añadir la entidad buscada al convenio: " + numeroConvenio, "Error creando la relacion", 2);
    }
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
}//GEN-LAST:event_btnAgregar_al_convenioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenuBusquedaEntidad;
    private javax.swing.JButton btnAgregar_al_convenio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btn_buscar_entidad;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogoBusquedaEntidad;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNitBusqueda;
    private javax.swing.JLabel lblNitResultado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreResultado;
    private javax.swing.JLabel lblTituloBusquedaEntidad;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JPanel panelDatosBusquedEntidad;
    private javax.swing.JPanel panelDatosBusqueda;
    private javax.swing.JPanel panelDescBusqueda;
    private javax.swing.JPanel panelResultadoBusqueda;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txt_Nit_Buscar;
    // End of variables declaration//GEN-END:variables

  private void deshabilitarCampos() {
    lblNombreResultado.setVisible(false);
    lblNitResultado.setVisible(false);
    txtDescripcion.setVisible(false);
    btnAgregar_al_convenio.setVisible(false);
  }
  
  private void cargarDatos(Entidad_convenio entidad) {
    habilitarCampos();
    lblNombreResultado.setText(entidad.getNombre_entidad());
    lblNitResultado.setText(entidad.getNIT_entidad());
    txtDescripcion.setText(entidad.getDescripcion_entidad());
  }
  
  private void habilitarCampos() {
    lblNombreResultado.setVisible(true);
    lblNitResultado.setVisible(true);
    txtDescripcion.setVisible(true);
    if (numeroConvenio != 0) {
      btnAgregar_al_convenio.setVisible(true);
    }
  }
  
  private void limpiarFormulario() {
    txt_Nit_Buscar.setText("");
    lblNitResultado.setText("");
    lblNombreResultado.setText("");
    txtDescripcion.setText("");
  }
}
