/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIConsultaConvenioNumero.java
 *
 * Created on 2/08/2012, 09:29:46 PM
 */
package Vista;

import Controlador.*;
import Estructural.*;
import Modelo.ICambioVista;
import Modelo.IServicioConvenios;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kmilo
 */
public class GUIConsultaConvenioNumero extends javax.swing.JFrame implements ICambioVista {

  private IServicioConvenios servicioConvenios;
  private ControlConvenio controlConvenio;
  private ControlEntidad controlEntidad;
  private ControlPresupuesto controlPresupuesto;
  private ControlRubros controlRubros;
  private Convenio convenio_global;
  private DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");

  /** Creates new form GUIConsultaConvenioNumero */
  public GUIConsultaConvenioNumero(IServicioConvenios servicioConvenios) throws RemoteException {
    initComponents();
    this.servicioConvenios = servicioConvenios;
    controlConvenio = new ControlConvenio(servicioConvenios);
    controlEntidad = new ControlEntidad(servicioConvenios);
    controlPresupuesto = new ControlPresupuesto(servicioConvenios);
    controlRubros = new ControlRubros(servicioConvenios);
    this.setLocationRelativeTo(null);
    lblNumeroConvenioValor.setVisible(false);
    lblFechaValor.setVisible(false);
    lblEstado.setVisible(false);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelConsultaNumero = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblImagenTitulo = new javax.swing.JLabel();
    panelDatosBaseConvenio = new javax.swing.JPanel();
    lblNumeroConvenio = new javax.swing.JLabel();
    txtNumeroConvenio = new javax.swing.JTextField();
    btnBuscar = new javax.swing.JButton();
    panelEntidades = new javax.swing.JPanel();
    panelDespEntidades = new javax.swing.JScrollPane();
    tablaEntidades = new javax.swing.JTable();
    btnEditarEntidad = new javax.swing.JButton();
    panelPresupuesto = new javax.swing.JPanel();
    scrollTablaRubro = new javax.swing.JScrollPane();
    tablaDatosRubros = new javax.swing.JTable();
    btnEditarRubro = new javax.swing.JButton();
    btnEjecutar = new javax.swing.JButton();
    btnAgregarRubro = new javax.swing.JButton();
    lblTotalvalor = new javax.swing.JLabel();
    lblTotal = new javax.swing.JLabel();
    panelDatosBaseConvenio1 = new javax.swing.JPanel();
    lblNumeroConvenioMostrar = new javax.swing.JLabel();
    lblNumeroConvenioValor = new javax.swing.JLabel();
    lblFecha = new javax.swing.JLabel();
    lblFechaValor = new javax.swing.JLabel();
    btnVariacion = new javax.swing.JButton();
    btnLiquidar = new javax.swing.JButton();
    lblEstado = new javax.swing.JLabel();
    btnSalir = new javax.swing.JButton();
    menuConsultaConveNumero = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Consulta de Convenios por número");

    panelConsultaNumero.setBackground(new java.awt.Color(255, 255, 255));

    lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24));
    lblTitulo.setText("Consulta de Convenio Suministrando el Número del mismo");

    lblImagenTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarConvenioGrande.png"))); // NOI18N

    panelDatosBaseConvenio.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosBaseConvenio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblNumeroConvenio.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNumeroConvenio.setText("Número Convenio");

    txtNumeroConvenio.setFont(new java.awt.Font("Calibri", 2, 13));
    txtNumeroConvenio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    btnBuscar.setFont(new java.awt.Font("Calibri", 3, 13));
    btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarConvenio.png"))); // NOI18N
    btnBuscar.setText("Buscar");
    btnBuscar.setBorder(null);
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelDatosBaseConvenioLayout = new javax.swing.GroupLayout(panelDatosBaseConvenio);
    panelDatosBaseConvenio.setLayout(panelDatosBaseConvenioLayout);
    panelDatosBaseConvenioLayout.setHorizontalGroup(
      panelDatosBaseConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosBaseConvenioLayout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(lblNumeroConvenio)
        .addGap(18, 18, 18)
        .addComponent(txtNumeroConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(34, 34, 34)
        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(23, Short.MAX_VALUE))
    );
    panelDatosBaseConvenioLayout.setVerticalGroup(
      panelDatosBaseConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosBaseConvenioLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosBaseConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosBaseConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(txtNumeroConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(lblNumeroConvenio))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelEntidades.setBackground(new java.awt.Color(255, 255, 255));
    panelEntidades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entidades Participantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    tablaEntidades.setFont(new java.awt.Font("Calibri", 2, 13));
    tablaEntidades.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "NIT Entidad", "Nombre Entidad", "Descripción"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, true, true
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    panelDespEntidades.setViewportView(tablaEntidades);

    btnEditarEntidad.setFont(new java.awt.Font("Calibri", 3, 13));
    btnEditarEntidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editarEntidad.png"))); // NOI18N
    btnEditarEntidad.setText("Editar la Entidad Seleccionada");
    btnEditarEntidad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarEntidadActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelEntidadesLayout = new javax.swing.GroupLayout(panelEntidades);
    panelEntidades.setLayout(panelEntidadesLayout);
    panelEntidadesLayout.setHorizontalGroup(
      panelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntidadesLayout.createSequentialGroup()
        .addContainerGap(714, Short.MAX_VALUE)
        .addComponent(btnEditarEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(panelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelEntidadesLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(panelDespEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
          .addContainerGap()))
    );
    panelEntidadesLayout.setVerticalGroup(
      panelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntidadesLayout.createSequentialGroup()
        .addContainerGap(146, Short.MAX_VALUE)
        .addComponent(btnEditarEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(panelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelEntidadesLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(panelDespEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(37, Short.MAX_VALUE)))
    );

    panelPresupuesto.setBackground(new java.awt.Color(255, 255, 255));
    panelPresupuesto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Presupuesto del convenio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    tablaDatosRubros.setFont(new java.awt.Font("Calibri", 2, 13));
    tablaDatosRubros.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID del rubro", "Descripción Rubro", "Cantidad", "Valor Unitario", "Total Rubro", "Ejecutado a la fecha"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, true, true, true, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    scrollTablaRubro.setViewportView(tablaDatosRubros);

    btnEditarRubro.setFont(new java.awt.Font("Calibri", 3, 13));
    btnEditarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editarRubro.png"))); // NOI18N
    btnEditarRubro.setText("Editar Rubro Seleccionado");
    btnEditarRubro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarRubroActionPerformed(evt);
      }
    });

    btnEjecutar.setFont(new java.awt.Font("Calibri", 3, 13));
    btnEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ejecutarPresupuesto.png"))); // NOI18N
    btnEjecutar.setText("Ejecutar Presupuesto del rubro Seleccionado");
    btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEjecutarActionPerformed(evt);
      }
    });

    btnAgregarRubro.setFont(new java.awt.Font("Calibri", 3, 13));
    btnAgregarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarRubro.png"))); // NOI18N
    btnAgregarRubro.setText("Agregar Nuevo Rubro");
    btnAgregarRubro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAgregarRubroActionPerformed(evt);
      }
    });

    lblTotalvalor.setFont(new java.awt.Font("Calibri", 2, 13));
    lblTotalvalor.setText("valor total presupuesto");

    lblTotal.setFont(new java.awt.Font("Calibri", 2, 13));
    lblTotal.setText("Total Presupuesto (sumatoria de Rubros actuales)");

    javax.swing.GroupLayout panelPresupuestoLayout = new javax.swing.GroupLayout(panelPresupuesto);
    panelPresupuesto.setLayout(panelPresupuestoLayout);
    panelPresupuestoLayout.setHorizontalGroup(
      panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelPresupuestoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPresupuestoLayout.createSequentialGroup()
            .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(63, 63, 63)
            .addComponent(btnAgregarRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
            .addComponent(btnEditarRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(scrollTablaRubro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
          .addGroup(panelPresupuestoLayout.createSequentialGroup()
            .addComponent(lblTotal)
            .addGap(18, 18, 18)
            .addComponent(lblTotalvalor)))
        .addContainerGap())
    );
    panelPresupuestoLayout.setVerticalGroup(
      panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelPresupuestoLayout.createSequentialGroup()
        .addComponent(scrollTablaRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnEditarRubro)
          .addComponent(btnEjecutar)
          .addComponent(btnAgregarRubro))
        .addGap(18, 18, 18)
        .addGroup(panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTotal)
          .addComponent(lblTotalvalor)))
    );

    panelDatosBaseConvenio1.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosBaseConvenio1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Convenio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblNumeroConvenioMostrar.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNumeroConvenioMostrar.setText("Numero Convenio");

    lblNumeroConvenioValor.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNumeroConvenioValor.setText("Numero Convenio");

    lblFecha.setFont(new java.awt.Font("Calibri", 2, 13));
    lblFecha.setText("Fecha Suscripcion");

    lblFechaValor.setFont(new java.awt.Font("Calibri", 2, 13));
    lblFechaValor.setText("jLabel4");

    btnVariacion.setFont(new java.awt.Font("Calibri", 3, 13));
    btnVariacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/variacion.png"))); // NOI18N
    btnVariacion.setText("Variación de tiempo");
    btnVariacion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVariacionActionPerformed(evt);
      }
    });

    btnLiquidar.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    btnLiquidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/liquidarConvenio.png"))); // NOI18N
    btnLiquidar.setText("Liquidar");
    btnLiquidar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLiquidarActionPerformed(evt);
      }
    });

    lblEstado.setText("Estado");

    javax.swing.GroupLayout panelDatosBaseConvenio1Layout = new javax.swing.GroupLayout(panelDatosBaseConvenio1);
    panelDatosBaseConvenio1.setLayout(panelDatosBaseConvenio1Layout);
    panelDatosBaseConvenio1Layout.setHorizontalGroup(
      panelDatosBaseConvenio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosBaseConvenio1Layout.createSequentialGroup()
        .addGroup(panelDatosBaseConvenio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosBaseConvenio1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblNumeroConvenioMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(36, 36, 36)
            .addComponent(lblNumeroConvenioValor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelDatosBaseConvenio1Layout.createSequentialGroup()
            .addGap(51, 51, 51)
            .addComponent(btnVariacion)))
        .addGap(18, 18, 18)
        .addGroup(panelDatosBaseConvenio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosBaseConvenio1Layout.createSequentialGroup()
            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblFechaValor)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
            .addComponent(lblEstado)
            .addGap(35, 35, 35))
          .addGroup(panelDatosBaseConvenio1Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(btnLiquidar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(89, Short.MAX_VALUE))))
    );
    panelDatosBaseConvenio1Layout.setVerticalGroup(
      panelDatosBaseConvenio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosBaseConvenio1Layout.createSequentialGroup()
        .addGroup(panelDatosBaseConvenio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNumeroConvenioMostrar)
          .addComponent(lblNumeroConvenioValor)
          .addComponent(lblFecha)
          .addComponent(lblFechaValor)
          .addComponent(lblEstado))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelDatosBaseConvenio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnLiquidar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnVariacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnSalir.setFont(new java.awt.Font("Calibri", 3, 13));
    btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
    btnSalir.setText("Salir");
    btnSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelConsultaNumeroLayout = new javax.swing.GroupLayout(panelConsultaNumero);
    panelConsultaNumero.setLayout(panelConsultaNumeroLayout);
    panelConsultaNumeroLayout.setHorizontalGroup(
      panelConsultaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelConsultaNumeroLayout.createSequentialGroup()
        .addGroup(panelConsultaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelConsultaNumeroLayout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(panelConsultaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelConsultaNumeroLayout.createSequentialGroup()
                .addComponent(panelDatosBaseConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDatosBaseConvenio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(panelConsultaNumeroLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(30, 30, 30)
                .addComponent(lblImagenTitulo))
              .addComponent(panelEntidades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultaNumeroLayout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(panelPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultaNumeroLayout.createSequentialGroup()
            .addContainerGap(856, Short.MAX_VALUE)
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    panelConsultaNumeroLayout.setVerticalGroup(
      panelConsultaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelConsultaNumeroLayout.createSequentialGroup()
        .addGroup(panelConsultaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelConsultaNumeroLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblImagenTitulo))
          .addGroup(panelConsultaNumeroLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(lblTitulo)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelConsultaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelDatosBaseConvenio1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(panelDatosBaseConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSalir)
        .addContainerGap(22, Short.MAX_VALUE))
    );

    menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
    menuArchivo.setText("Archivo");
    menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13));
    menuConsultaConveNumero.add(menuArchivo);

    menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
    menuAyuda.setText("Ayuda");
    menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13));
    menuConsultaConveNumero.add(menuAyuda);

    setJMenuBar(menuConsultaConveNumero);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(panelConsultaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelConsultaNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
// TODO add your handling code here:
  int numeroConvenio = 0;
  boolean controlDatos = true;
  if (txtNumeroConvenio.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Digitar un número de Convenio", "Error número Convenio", 0);
    controlDatos = false;
  } else {
    try {
      numeroConvenio = Integer.parseInt(txtNumeroConvenio.getText().trim());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Debe Digitar un número de Convenio que se\n"
              + "contenga digitos entre 0 y 9 Ej: 0674", "Error número Convenio", 0);
      controlDatos = false;
    }
  }
  if (controlDatos) {
    try {
      Convenio convenio = controlConvenio.ConsultaConvenioNumero(numeroConvenio);
      if (convenio != null) {
        convenio_global = convenio;
        mostrarDatosConvenio();
        ArrayList<Entidad_convenio> entidades = controlEntidad.ConsultaEntidades(convenio.getNumero_convenio());
        Presupuesto presupuesto = controlPresupuesto.PresupuestoPorConvenio(convenio.getNumero_convenio());
        if (entidades.isEmpty()) {
          JOptionPane.showMessageDialog(rootPane, "No se han vinculado entidades al convenio buscado", "Sin entidades vinculadas", 1);
        } else {
          cargarEntidades(entidades);
        }
        if (presupuesto == null) {
          JOptionPane.showMessageDialog(rootPane, "No se ha establecido un presupuesto para el convenio buscado", "No se ha creado Presupuesto", 1);
        } else {
          cargarRubros(presupuesto);
        }
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se encontro un convenio con el numero ingresado", "Convenio no existe", 1);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}//GEN-LAST:event_btnBuscarActionPerformed

private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
// TODO add your handling code here:
  int filaSeleccionada = tablaDatosRubros.getSelectedRow();
  if (filaSeleccionada != -1 && filaSeleccionada != tablaDatosRubros.getRowCount() - 1) {
    int id_rubro = Integer.parseInt(tablaDatosRubros.getValueAt(filaSeleccionada, 0).toString());
    try {
      Rubro_presupuestal rubro = controlRubros.ConsultaRubroPorId_Rubro(id_rubro);
      if (rubro != null) {
        EjecucionPresupuesto ejecucionPresupuesto = new EjecucionPresupuesto(servicioConvenios, rubro);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  } else {
    JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un rubro para Ejecutar Presupuesto", "Seleccione rubro", 0);
  }
}//GEN-LAST:event_btnEjecutarActionPerformed

private void btnEditarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRubroActionPerformed
// TODO add your handling code here:
  int filaSeleccionada = tablaDatosRubros.getSelectedRow();
  if (filaSeleccionada != -1 && filaSeleccionada != tablaDatosRubros.getRowCount() - 1) {
    int id_rubro = Integer.parseInt(tablaDatosRubros.getValueAt(filaSeleccionada, 0).toString());
    try {
      GUIEditarRubro guiEditarRubro = new GUIEditarRubro(servicioConvenios, id_rubro, convenio_global.getNumero_convenio());
      guiEditarRubro.show();
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  } else {
    JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un rubro para Editar", "Seleccione rubro", 0);
  }
}//GEN-LAST:event_btnEditarRubroActionPerformed

private void btnAgregarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRubroActionPerformed
// TODO add your handling code here:
  int id_presupuesto = 0;
  Date fecha_presupuesto = null;
  Presupuesto presupuesto = null;
  try {
    presupuesto = controlPresupuesto.PresupuestoPorConvenio(convenio_global.getNumero_convenio());
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
  if (presupuesto != null) {
    try {
      GUIAdicionRubro guiAdicionRubro = new GUIAdicionRubro(servicioConvenios, convenio_global.getNumero_convenio());
      guiAdicionRubro.show();
    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
  } else {
    try {
      Date fecha = new Date();
      fecha_presupuesto = formatoFecha.parse(fecha.toString());
      presupuesto = new Presupuesto(id_presupuesto, fecha_presupuesto, convenio_global.getNumero_convenio());
      boolean controlAdicion = controlPresupuesto.AdicionPresupuesto(presupuesto);
      if (controlAdicion) {
        GUIAdicionRubro guiAdicionRubro = new GUIAdicionRubro(servicioConvenios, convenio_global.getNumero_convenio());
        guiAdicionRubro.show();
      } else {
        JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un problema, por favor contacta al administrador", "Falla del sistema", 2);
      }
    } catch (Exception e) {
    }
  }
}//GEN-LAST:event_btnAgregarRubroActionPerformed

private void btnEditarEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEntidadActionPerformed
// TODO add your handling code here:
  int filaSeleccionada = tablaEntidades.getSelectedRow();
  if (filaSeleccionada != -1) {
    String Nit = tablaEntidades.getValueAt(filaSeleccionada, 0).toString();
    try {
      Entidad_convenio entidad = controlEntidad.ConsultaEntidad(Nit);
      GUIEditarEntidad guiEditarEntidad = new GUIEditarEntidad(servicioConvenios, entidad);
      guiEditarEntidad.show();
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  } else {
    JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una Entidad para Editar", "Seleccione Entidad", 0);
  }
}//GEN-LAST:event_btnEditarEntidadActionPerformed

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
  this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

private void btnVariacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVariacionActionPerformed
// TODO add your handling code here:
  try {
    if (convenio_global != null) {
      VariacionTiempoConvenio variacionTiempoConvenio = new VariacionTiempoConvenio(servicioConvenios, convenio_global);
    } else {
      JOptionPane.showMessageDialog(rootPane, "Debe buscar un convenio primero", "Buscar Convenio", 0);
    }
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
}//GEN-LAST:event_btnVariacionActionPerformed

private void btnLiquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiquidarActionPerformed
// TODO add your handling code here:
  if (convenio_global != null) {
    try {
      GUILiquidarConvenio guiLiquidarConvenio = new GUILiquidarConvenio(servicioConvenios, convenio_global);
      guiLiquidarConvenio.show();
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  } else {
    JOptionPane.showMessageDialog(rootPane, "Debe buscar un convenio primero", "Buscar Convenio", 0);
  }
}//GEN-LAST:event_btnLiquidarActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAgregarRubro;
  private javax.swing.JButton btnBuscar;
  private javax.swing.JButton btnEditarEntidad;
  private javax.swing.JButton btnEditarRubro;
  private javax.swing.JButton btnEjecutar;
  private javax.swing.JButton btnLiquidar;
  private javax.swing.JButton btnSalir;
  private javax.swing.JButton btnVariacion;
  private javax.swing.JLabel lblEstado;
  private javax.swing.JLabel lblFecha;
  private javax.swing.JLabel lblFechaValor;
  private javax.swing.JLabel lblImagenTitulo;
  private javax.swing.JLabel lblNumeroConvenio;
  private javax.swing.JLabel lblNumeroConvenioMostrar;
  private javax.swing.JLabel lblNumeroConvenioValor;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JLabel lblTotal;
  private javax.swing.JLabel lblTotalvalor;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JMenuBar menuConsultaConveNumero;
  private javax.swing.JPanel panelConsultaNumero;
  private javax.swing.JPanel panelDatosBaseConvenio;
  private javax.swing.JPanel panelDatosBaseConvenio1;
  private javax.swing.JScrollPane panelDespEntidades;
  private javax.swing.JPanel panelEntidades;
  private javax.swing.JPanel panelPresupuesto;
  private javax.swing.JScrollPane scrollTablaRubro;
  private javax.swing.JTable tablaDatosRubros;
  private javax.swing.JTable tablaEntidades;
  private javax.swing.JTextField txtNumeroConvenio;
  // End of variables declaration//GEN-END:variables

  private void mostrarEntidades() throws RemoteException {
    ArrayList entidades = new ArrayList<Entidad_convenio>();
    if (convenio_global != null) {
      entidades = controlEntidad.ConsultaEntidades(convenio_global.getNumero_convenio());
      cargarEntidades(entidades);
    }
  }

  private void cargarEntidades(ArrayList<Entidad_convenio> entidades) {
    int fila = 0;
    for (int i = 0; i < entidades.size(); i++) {
      if (tablaEntidades.getRowCount() == fila) {
        DefaultTableModel tablaTemp = (DefaultTableModel) tablaEntidades.getModel();
        Object nuevo[] = {null, null, null};
        tablaTemp.addRow(nuevo);
      }
      tablaEntidades.setValueAt(entidades.get(i).getNIT_entidad(), i, 0);
      tablaEntidades.setValueAt(entidades.get(i).getNombre_entidad(), i, 1);
      tablaEntidades.setValueAt(entidades.get(i).getDescripcion_entidad(), i, 2);
      fila++;
    }
    if (tablaEntidades.getRowCount() > fila) {
      DefaultTableModel tablaTemp = (DefaultTableModel) tablaEntidades.getModel();
      tablaTemp.removeRow(fila);
    }
  }

  private void cargarRubros(Presupuesto presupuesto) throws RemoteException {
    limpiarDatosPresupuesto();
    ArrayList<Rubro_presupuestal> rubros = controlRubros.ConsultaRubrosPorPresupuesto(presupuesto);
    if (!rubros.isEmpty()) {
      int numeroColumnas = tablaDatosRubros.getColumnCount();
      int fila = 0;
      for (int i = 0; i < rubros.size(); i++) {
        //Creando filas
        if (tablaDatosRubros.getRowCount() == fila) {
          DefaultTableModel tablaTemp = (DefaultTableModel) tablaDatosRubros.getModel();
          Object nuevo[] = new Object[numeroColumnas];
          tablaTemp.addRow(nuevo);
        }
        int cantidad = rubros.get(i).getCantidad();
        double valor = rubros.get(i).getValor_unitario();
        double total = cantidad * valor;
        tablaDatosRubros.setValueAt(rubros.get(i).getId_rubro(), fila, 0);
        tablaDatosRubros.setValueAt(rubros.get(i).getDescripcion_rubro(), fila, 1);
        tablaDatosRubros.setValueAt(cantidad, fila, 2);
        tablaDatosRubros.setValueAt(valor, fila, 3);
        tablaDatosRubros.setValueAt(total, fila, 4);
        ArrayList<Ejecucion_presupuesto> ejecuciones = controlPresupuesto.ConsultaEjecucionPorRubro(rubros.get(i).getId_rubro());
        double ejecutado_fecha = 0;
        if (!ejecuciones.isEmpty()) {
          for (int k = 0; k < ejecuciones.size(); k++) {
            ejecutado_fecha = ejecutado_fecha + ejecuciones.get(k).getMonto_ejecutado();
          }
        }
        tablaDatosRubros.setValueAt(ejecutado_fecha, fila, 5);
        fila++;
      }
      if (tablaDatosRubros.getRowCount() > fila) {
        DefaultTableModel tablaTemp = (DefaultTableModel) tablaDatosRubros.getModel();
        tablaTemp.removeRow(fila);
      }
      int numeroFilas = tablaDatosRubros.getRowCount();
      double totalPresupuesto = 0;
      double totalEjecutado = 0;
      for (int i = 0; i < numeroFilas; i++) {
        totalPresupuesto = totalPresupuesto + Double.parseDouble(tablaDatosRubros.getValueAt(i, 4).toString());
        totalEjecutado = totalEjecutado + Double.parseDouble(tablaDatosRubros.getValueAt(i, 5).toString());
      }
      DefaultTableModel tablaTemp = (DefaultTableModel) tablaDatosRubros.getModel();
      Object nuevo[] = new Object[numeroColumnas];
      tablaTemp.addRow(nuevo);
      tablaDatosRubros.setValueAt("TOTAL", tablaDatosRubros.getRowCount() - 1, 3);
      tablaDatosRubros.setValueAt(totalPresupuesto, tablaDatosRubros.getRowCount() - 1, 4);
      tablaDatosRubros.setValueAt(totalEjecutado, tablaDatosRubros.getRowCount() - 1, 5);
      lblTotalvalor.setText(String.valueOf(totalPresupuesto));
    }
  }

  private void mostrarValoresPresupuesto() {
    limpiarDatosPresupuesto();
    Presupuesto presupuesto = null;
    try {
      if (convenio_global != null) {
        presupuesto = controlPresupuesto.PresupuestoPorConvenio(convenio_global.getNumero_convenio());
        if (presupuesto != null) {
          cargarRubros(presupuesto);
        }
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }

  private void limpiarDatosPresupuesto() {
    int columnas = tablaDatosRubros.getColumnCount();
    int filas = tablaDatosRubros.getRowCount();
    for (int i = 0; i < filas; i++) {
      for (int j = 0; j < columnas; j++) {
        tablaDatosRubros.setValueAt("", i, j);
      }
    }
  }

  private void mostrarDatosConvenio() {
    lblNumeroConvenioValor.setText(String.valueOf(convenio_global.getNumero_convenio()));
    lblNumeroConvenioValor.setVisible(true);
    lblFechaValor.setText(String.valueOf(convenio_global.getFecha_inicio_convenio()));
    lblFechaValor.setVisible(true);
    lblEstado.setText(convenio_global.getEstado_convenio());
    lblEstado.setVisible(true);
  }

  @Override
  public void CambioVista() throws RemoteException {
    mostrarEntidades();
    mostrarValoresPresupuesto();
    actualizarConvenio();
  }

  private void actualizarConvenio() {
    try {
      convenio_global = controlConvenio.ConsultaConvenioNumero(convenio_global.getNumero_convenio());
      lblEstado.setText(convenio_global.getEstado_convenio());
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}
