/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIEjecucionPresupuesto.java
 *
 * Created on 14/08/2012, 11:18:13 PM
 */
package Vista;

import Controlador.ControlPresupuesto;
import Controlador.ControlRubros;
import Estructural.Ejecucion_presupuesto;
import Estructural.Rubro_presupuestal;
import Modelo.IServicioConvenios;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kmilo
 */
public class GUIEjecucionPresupuesto extends javax.swing.JFrame {

  private IServicioConvenios servicioConvenios;
  private Rubro_presupuestal rubro;
  private ControlRubros controlRubros;
  private ControlPresupuesto controlPresupuesto;
  private DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");

  /** Creates new form GUIEjecucionPresupuesto */
  public GUIEjecucionPresupuesto(IServicioConvenios servicioConvenios, Rubro_presupuestal rubro) throws RemoteException {
    initComponents();
    this.servicioConvenios = servicioConvenios;
    this.rubro = rubro;
    controlRubros = new ControlRubros(servicioConvenios);
    controlPresupuesto = new ControlPresupuesto(servicioConvenios);
    this.setLocationRelativeTo(null);
    lblMensaje.setVisible(false);
    cargarDatosRubro();
    cargarEjecuciones();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelEjecucionPresupuestal = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblIcono = new javax.swing.JLabel();
    panelRubroInfo = new javax.swing.JPanel();
    lblId = new javax.swing.JLabel();
    lblIdValor = new javax.swing.JLabel();
    lblCantidad = new javax.swing.JLabel();
    lblCantidadValor = new javax.swing.JLabel();
    lblValorUnitario = new javax.swing.JLabel();
    lblValorUnitarioValor = new javax.swing.JLabel();
    lblValorTotal = new javax.swing.JLabel();
    lblValorTotalValor = new javax.swing.JLabel();
    panelEjecutadoFecha = new javax.swing.JPanel();
    scrollEjecuciones = new javax.swing.JScrollPane();
    tablaEjecuciones = new javax.swing.JTable();
    lblTotalEjecutado = new javax.swing.JLabel();
    lblTotalEjecutadoValor = new javax.swing.JLabel();
    lblPendienteEjecutar = new javax.swing.JLabel();
    lblPendienteEjecutarValor = new javax.swing.JLabel();
    lblMensaje = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtDescripcion = new javax.swing.JTextPane();
    panelEjecucionInfo = new javax.swing.JPanel();
    lblMonto = new javax.swing.JLabel();
    txtMonto = new javax.swing.JTextField();
    lblFecha = new javax.swing.JLabel();
    comboFecha = new datechooser.beans.DateChooserCombo();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtDescripcionEjecucion = new javax.swing.JTextPane();
    btnEjecutar = new javax.swing.JButton();
    btnSalir = new javax.swing.JButton();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Ejecución Presupuestal");

    panelEjecucionPresupuestal.setBackground(new java.awt.Color(255, 255, 255));

    lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
    lblTitulo.setText("Ejecucion Presupuestal");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ejecutarPresupuestoGrande.png"))); // NOI18N

    panelRubroInfo.setBackground(new java.awt.Color(255, 255, 255));
    panelRubroInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del Rubro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblId.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblId.setText("Id del Rubro");

    lblIdValor.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblIdValor.setText("Id del Rubro");

    lblCantidad.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblCantidad.setText("Cantidad");

    lblCantidadValor.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblCantidadValor.setText("Cantidad");

    lblValorUnitario.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblValorUnitario.setText("Valor unitario");

    lblValorUnitarioValor.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblValorUnitarioValor.setText("Valor unitario");

    lblValorTotal.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblValorTotal.setText("Valor Total");

    lblValorTotalValor.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblValorTotalValor.setText("Valor Total");

    panelEjecutadoFecha.setBackground(new java.awt.Color(255, 255, 255));
    panelEjecutadoFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ejecuciones a la fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    tablaEjecuciones.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    tablaEjecuciones.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Monto ejecutado", "Fecha Ejecución", "Descripción"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, true, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    scrollEjecuciones.setViewportView(tablaEjecuciones);

    javax.swing.GroupLayout panelEjecutadoFechaLayout = new javax.swing.GroupLayout(panelEjecutadoFecha);
    panelEjecutadoFecha.setLayout(panelEjecutadoFechaLayout);
    panelEjecutadoFechaLayout.setHorizontalGroup(
      panelEjecutadoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEjecutadoFechaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollEjecuciones, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        .addContainerGap())
    );
    panelEjecutadoFechaLayout.setVerticalGroup(
      panelEjecutadoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEjecutadoFechaLayout.createSequentialGroup()
        .addComponent(scrollEjecuciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    lblTotalEjecutado.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblTotalEjecutado.setText("Total Ejecutado");

    lblTotalEjecutadoValor.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblTotalEjecutadoValor.setText("0");

    lblPendienteEjecutar.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblPendienteEjecutar.setText("Pendiente por Ejecutar");

    lblPendienteEjecutarValor.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblPendienteEjecutarValor.setText("0");

    lblMensaje.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
    lblMensaje.setForeground(new java.awt.Color(255, 0, 51));
    lblMensaje.setText("Este Rubro ya fue Ejecutado en su totalidad");

    txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N
    txtDescripcion.setEditable(false);
    txtDescripcion.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    jScrollPane1.setViewportView(txtDescripcion);

    javax.swing.GroupLayout panelRubroInfoLayout = new javax.swing.GroupLayout(panelRubroInfo);
    panelRubroInfo.setLayout(panelRubroInfoLayout);
    panelRubroInfoLayout.setHorizontalGroup(
      panelRubroInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelRubroInfoLayout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addGroup(panelRubroInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblId)
          .addComponent(lblValorUnitario))
        .addGap(49, 49, 49)
        .addGroup(panelRubroInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblIdValor)
          .addComponent(lblValorUnitarioValor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
        .addGroup(panelRubroInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblCantidad)
          .addComponent(lblValorTotal))
        .addGap(72, 72, 72)
        .addGroup(panelRubroInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblCantidadValor)
          .addComponent(lblValorTotalValor))
        .addGap(37, 37, 37)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRubroInfoLayout.createSequentialGroup()
        .addContainerGap(233, Short.MAX_VALUE)
        .addComponent(lblTotalEjecutado)
        .addGap(33, 33, 33)
        .addComponent(lblTotalEjecutadoValor)
        .addGap(97, 97, 97)
        .addComponent(lblPendienteEjecutar)
        .addGap(18, 18, 18)
        .addComponent(lblPendienteEjecutarValor)
        .addGap(221, 221, 221))
      .addGroup(panelRubroInfoLayout.createSequentialGroup()
        .addGap(271, 271, 271)
        .addComponent(lblMensaje)
        .addContainerGap(286, Short.MAX_VALUE))
      .addGroup(panelRubroInfoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(panelEjecutadoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    panelRubroInfoLayout.setVerticalGroup(
      panelRubroInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelRubroInfoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelRubroInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelRubroInfoLayout.createSequentialGroup()
            .addGroup(panelRubroInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelRubroInfoLayout.createSequentialGroup()
                .addComponent(lblId)
                .addGap(18, 18, 18)
                .addComponent(lblValorUnitario))
              .addGroup(panelRubroInfoLayout.createSequentialGroup()
                .addComponent(lblCantidad)
                .addGap(18, 18, 18)
                .addComponent(lblValorTotal))
              .addGroup(panelRubroInfoLayout.createSequentialGroup()
                .addComponent(lblCantidadValor)
                .addGap(18, 18, 18)
                .addComponent(lblValorTotalValor)))
            .addGap(13, 13, 13)
            .addComponent(lblMensaje))
          .addGroup(panelRubroInfoLayout.createSequentialGroup()
            .addComponent(lblIdValor)
            .addGap(18, 18, 18)
            .addComponent(lblValorUnitarioValor))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelEjecutadoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
        .addGroup(panelRubroInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTotalEjecutado)
          .addComponent(lblTotalEjecutadoValor)
          .addComponent(lblPendienteEjecutar)
          .addComponent(lblPendienteEjecutarValor))
        .addContainerGap())
    );

    panelEjecucionInfo.setBackground(new java.awt.Color(255, 255, 255));
    panelEjecucionInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de la Ejecución", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblMonto.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblMonto.setText("Monto a Ejecutar");

    txtMonto.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    txtMonto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblFecha.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    lblFecha.setText("Fecha Ejecución");

    txtDescripcionEjecucion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción de la Ejecución", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N
    jScrollPane2.setViewportView(txtDescripcionEjecucion);

    javax.swing.GroupLayout panelEjecucionInfoLayout = new javax.swing.GroupLayout(panelEjecucionInfo);
    panelEjecucionInfo.setLayout(panelEjecucionInfoLayout);
    panelEjecucionInfoLayout.setHorizontalGroup(
      panelEjecucionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEjecucionInfoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelEjecucionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
          .addGroup(panelEjecucionInfoLayout.createSequentialGroup()
            .addComponent(lblMonto)
            .addGap(44, 44, 44)
            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
            .addComponent(lblFecha)
            .addGap(35, 35, 35)
            .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    panelEjecucionInfoLayout.setVerticalGroup(
      panelEjecucionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEjecucionInfoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelEjecucionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(panelEjecucionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblMonto)
            .addComponent(lblFecha)
            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnEjecutar.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    btnEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ejecutarPresupuesto.png"))); // NOI18N
    btnEjecutar.setText("Ejecutar");
    btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEjecutarActionPerformed(evt);
      }
    });

    btnSalir.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
    btnSalir.setText("Salir");
    btnSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelEjecucionPresupuestalLayout = new javax.swing.GroupLayout(panelEjecucionPresupuestal);
    panelEjecucionPresupuestal.setLayout(panelEjecucionPresupuestalLayout);
    panelEjecucionPresupuestalLayout.setHorizontalGroup(
      panelEjecucionPresupuestalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEjecucionPresupuestalLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelEjecucionPresupuestalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelEjecucionPresupuestalLayout.createSequentialGroup()
            .addComponent(lblTitulo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblIcono))
          .addGroup(panelEjecucionPresupuestalLayout.createSequentialGroup()
            .addComponent(panelEjecucionInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(panelEjecucionPresupuestalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(panelRubroInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelEjecucionPresupuestalLayout.setVerticalGroup(
      panelEjecucionPresupuestalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEjecucionPresupuestalLayout.createSequentialGroup()
        .addGroup(panelEjecucionPresupuestalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelEjecucionPresupuestalLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblIcono))
          .addGroup(panelEjecucionPresupuestalLayout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(lblTitulo)))
        .addGap(17, 17, 17)
        .addComponent(panelRubroInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelEjecucionPresupuestalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelEjecucionPresupuestalLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(panelEjecucionInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelEjecucionPresupuestalLayout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(btnEjecutar)
            .addGap(53, 53, 53)
            .addComponent(btnSalir)))
        .addContainerGap())
    );

    menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
    menuArchivo.setText("Archivo");
    menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuArchivo);

    menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
    menuAyuda.setText("Ayuda");
    menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuAyuda);

    setJMenuBar(barraMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelEjecucionPresupuestal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelEjecucionPresupuestal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
// TODO add your handling code here:
  boolean controlDatos = true;
  double monto = 0;
  Date fechaEjecucion = null;
  String descripcionEjecucion = "";
  if (txtMonto.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Digitar un Monto a Ejecutar", "Error Monto", 0);
    controlDatos = false;
  } else {
    try {
      monto = Double.parseDouble(txtMonto.getText().trim());
      if (monto <= Double.parseDouble(lblPendienteEjecutarValor.getText().trim()) && monto > 0) {
      } else {
        JOptionPane.showMessageDialog(rootPane, "Debe Digitar un Monto que no supere el valor\n "
                + "pendiente por ejecutar y que se mayor de cero (0)", "Error Monto", 0);
        controlDatos = false;
      }
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Debe Digitar un Monto que\n"
              + "contenga digitos entre 0 y 9 Ej: 9200", "Error Monto", 0);
      controlDatos = false;
      System.out.println(e.getMessage());
    }
  }
  if (txtDescripcionEjecucion.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Digitar una Descripción para la ejecucuón", "Error Descripción", 0);
    controlDatos = false;
  } else {
    descripcionEjecucion = txtDescripcionEjecucion.getText().trim();
  }
  if (controlDatos) {
    try {
      fechaEjecucion = formatoFecha.parse(comboFecha.getText());
      boolean controlAdicion = false;
      Ejecucion_presupuesto ejecucion = new Ejecucion_presupuesto(0, monto, fechaEjecucion, descripcionEjecucion, rubro.getId_rubro());
      controlAdicion = controlPresupuesto.AdicionEjecucion_Presupuesto(ejecucion);
      if (controlAdicion) {
        JOptionPane.showMessageDialog(rootPane, "Ejecución presupuestal realizada con exito", "Ejecución realizada", 1);
        limpiarFormulario();
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se pudo realizar la ejecución de presupuesto", "Error en la ejecución", 2);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}//GEN-LAST:event_btnEjecutarActionPerformed

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
  this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JButton btnEjecutar;
  private javax.swing.JButton btnSalir;
  private datechooser.beans.DateChooserCombo comboFecha;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel lblCantidad;
  private javax.swing.JLabel lblCantidadValor;
  private javax.swing.JLabel lblFecha;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JLabel lblId;
  private javax.swing.JLabel lblIdValor;
  private javax.swing.JLabel lblMensaje;
  private javax.swing.JLabel lblMonto;
  private javax.swing.JLabel lblPendienteEjecutar;
  private javax.swing.JLabel lblPendienteEjecutarValor;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JLabel lblTotalEjecutado;
  private javax.swing.JLabel lblTotalEjecutadoValor;
  private javax.swing.JLabel lblValorTotal;
  private javax.swing.JLabel lblValorTotalValor;
  private javax.swing.JLabel lblValorUnitario;
  private javax.swing.JLabel lblValorUnitarioValor;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JPanel panelEjecucionInfo;
  private javax.swing.JPanel panelEjecucionPresupuestal;
  private javax.swing.JPanel panelEjecutadoFecha;
  private javax.swing.JPanel panelRubroInfo;
  private javax.swing.JScrollPane scrollEjecuciones;
  private javax.swing.JTable tablaEjecuciones;
  private javax.swing.JTextPane txtDescripcion;
  private javax.swing.JTextPane txtDescripcionEjecucion;
  private javax.swing.JTextField txtMonto;
  // End of variables declaration//GEN-END:variables

  void CambioVista() throws RemoteException {
    cargarEjecuciones();
  }

  private void cargarDatosRubro() {
    lblIdValor.setText(String.valueOf(rubro.getId_rubro()));
    lblCantidadValor.setText(String.valueOf(rubro.getCantidad()));
    txtDescripcion.setText(rubro.getDescripcion_rubro());
    txtDescripcion.setEditable(false);
    lblValorUnitarioValor.setText(String.valueOf(rubro.getValor_unitario()));
    double total = rubro.getCantidad() * rubro.getValor_unitario();
    lblValorTotalValor.setText(String.valueOf(total));
  }

  private void cargarEjecuciones() throws RemoteException {
    limpiarEjecuciones();
    ArrayList<Ejecucion_presupuesto> ejecuciones = controlPresupuesto.ConsultaEjecucionPorRubro(rubro.getId_rubro());
    if (!ejecuciones.isEmpty()) {
      int fila = 0;
      double totalEjecutado = 0;
      for (int i = 0; i < ejecuciones.size(); i++) {
        if (tablaEjecuciones.getRowCount() == fila) {
          DefaultTableModel tablaTemp = (DefaultTableModel) tablaEjecuciones.getModel();
          Object nuevo[] = {null, null, null};
          tablaTemp.addRow(nuevo);
        }
        totalEjecutado = totalEjecutado + ejecuciones.get(i).getMonto_ejecutado();
        tablaEjecuciones.setValueAt(ejecuciones.get(i).getMonto_ejecutado(), i, 0);
        tablaEjecuciones.setValueAt(ejecuciones.get(i).getFecha_ejecucion(), i, 1);
        tablaEjecuciones.setValueAt(ejecuciones.get(i).getDescripcion_ejecucion(), i, 2);
        fila++;
      }
      lblTotalEjecutadoValor.setText(String.valueOf(totalEjecutado));
      Double pendienteEjecutar = Double.parseDouble(lblValorTotalValor.getText().trim()) - Double.parseDouble(lblTotalEjecutadoValor.getText().trim());
      lblPendienteEjecutarValor.setText(String.valueOf(pendienteEjecutar));
      if (Double.parseDouble(lblPendienteEjecutarValor.getText().trim()) == 0) {
        lblMensaje.setVisible(true);
        btnEjecutar.setEnabled(false);
      } else {
        lblMensaje.setVisible(false);
        btnEjecutar.setEnabled(true);
      }
      if (tablaEjecuciones.getRowCount() > fila) {
        DefaultTableModel tablaTemp = (DefaultTableModel) tablaEjecuciones.getModel();
        tablaTemp.removeRow(fila);
      }
    } else {
      Double pendienteEjecutar = Double.parseDouble(lblValorTotalValor.getText().trim()) - Double.parseDouble(lblTotalEjecutadoValor.getText().trim());
      lblPendienteEjecutarValor.setText(String.valueOf(pendienteEjecutar));
      if (Double.parseDouble(lblPendienteEjecutarValor.getText().trim()) == 0) {
        lblMensaje.setVisible(true);
        btnEjecutar.setEnabled(false);
      } else {
        lblMensaje.setVisible(false);
        btnEjecutar.setEnabled(true);
      }
    }
  }

  private void limpiarEjecuciones() {
    int filas = tablaEjecuciones.getRowCount();
    for (int i = 0; i < filas; i++) {
      tablaEjecuciones.setValueAt("", i, 0);
      tablaEjecuciones.setValueAt("", i, 1);
      tablaEjecuciones.setValueAt("", i, 2);
    }
  }

  private void limpiarFormulario() {
    txtMonto.setText("");
    txtDescripcionEjecucion.setText("");
  }
}
