/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */
package Vista.Profesoral;

import Controlador.Profesoral.ControlModulo;
import Modelo.IServicioProfesoral;

/**
 *
 * @author juanpanlo
 */
public class GUIAdicionarModulo extends javax.swing.JFrame {

    private IServicioProfesoral servicioProfesoral;
    private ControlModulo controlModulo;

    /**
     * Creates new form GUIAdicionarModulo
     */
    public GUIAdicionarModulo(IServicioProfesoral servicioProfesoral) {
        initComponents();
        this.servicioProfesoral = servicioProfesoral;
        controlModulo = new ControlModulo(servicioProfesoral);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAddModulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar MOdulo Programa");

        panelAddModulo.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        lblTitulo.setText("Adición de nuevo Modulo");

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addModuleGrande.png"))); // NOI18N

        javax.swing.GroupLayout panelAddModuloLayout = new javax.swing.GroupLayout(panelAddModulo);
        panelAddModulo.setLayout(panelAddModuloLayout);
        panelAddModuloLayout.setHorizontalGroup(
            panelAddModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIcono)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        panelAddModuloLayout.setVerticalGroup(
            panelAddModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddModuloLayout.createSequentialGroup()
                .addGroup(panelAddModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddModuloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcono))
                    .addGroup(panelAddModuloLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTitulo)))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        barraMenu.add(menuArchivo);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
        menuAyuda.setText("Ayuda?");
        menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAddModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAddModulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JPanel panelAddModulo;
    // End of variables declaration//GEN-END:variables
}
