/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIAsignarViaticos.java
 *
 * Created on 10/11/2012, 01:46:02 PM
 */
package Vista.Profesoral;

/**
 *
 * @author Kmilo
 */
public class GUIAsignarViaticos extends javax.swing.JFrame {

  /** Creates new form GUIAsignarViaticos */
  public GUIAsignarViaticos() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelAsignarViaticos = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblIcono = new javax.swing.JLabel();
    panelDatosConferencista = new javax.swing.JPanel();
    lblCedula = new javax.swing.JLabel();
    txtCedula = new javax.swing.JTextField();
    btnBuscarConferencista = new javax.swing.JButton();
    lblNombres = new javax.swing.JLabel();
    txtNombres = new javax.swing.JTextField();
    txtApellidos = new javax.swing.JTextField();
    lblApellidos = new javax.swing.JLabel();
    lblCorreo = new javax.swing.JLabel();
    txtCorreo = new javax.swing.JTextField();
    lblCelular = new javax.swing.JLabel();
    txtCelular = new javax.swing.JTextField();
    panelDatosModulo = new javax.swing.JPanel();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Asignaci[on de Viaticos");

    panelAsignarViaticos.setBackground(new java.awt.Color(255, 255, 255));

    lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
    lblTitulo.setText("Asignación de Viaticos");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addViaticosGrande .png"))); // NOI18N

    panelDatosConferencista.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosConferencista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Conferencista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblCedula.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCedula.setText("Cedula");

    txtCedula.setFont(new java.awt.Font("Calibri", 2, 13));
    txtCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    btnBuscarConferencista.setFont(new java.awt.Font("Calibri", 3, 13));
    btnBuscarConferencista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarConvenio.png"))); // NOI18N
    btnBuscarConferencista.setText("Buscar");
    btnBuscarConferencista.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarConferencistaActionPerformed(evt);
      }
    });

    lblNombres.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNombres.setText("Nombres");

    txtNombres.setFont(new java.awt.Font("Calibri", 2, 13));
    txtNombres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    txtApellidos.setFont(new java.awt.Font("Calibri", 2, 13));
    txtApellidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblApellidos.setFont(new java.awt.Font("Calibri", 2, 13));
    lblApellidos.setText("Apellidos");

    lblCorreo.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCorreo.setText("Correo Electrónico");

    txtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblCelular.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCelular.setText("Celular");

    txtCelular.setFont(new java.awt.Font("Calibri", 2, 13));
    txtCelular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    javax.swing.GroupLayout panelDatosConferencistaLayout = new javax.swing.GroupLayout(panelDatosConferencista);
    panelDatosConferencista.setLayout(panelDatosConferencistaLayout);
    panelDatosConferencistaLayout.setHorizontalGroup(
      panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
            .addComponent(lblCedula)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addComponent(btnBuscarConferencista))
          .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
            .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosConferencistaLayout.createSequentialGroup()
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosConferencistaLayout.createSequentialGroup()
                .addComponent(lblNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
                .addComponent(lblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
              .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))))
        .addContainerGap())
    );
    panelDatosConferencistaLayout.setVerticalGroup(
      panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCedula)
          .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscarConferencista))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNombres)
          .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblApellidos)
          .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCorreo)
          .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblCelular))
        .addContainerGap())
    );

    panelDatosModulo.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosModulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Modulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    javax.swing.GroupLayout panelDatosModuloLayout = new javax.swing.GroupLayout(panelDatosModulo);
    panelDatosModulo.setLayout(panelDatosModuloLayout);
    panelDatosModuloLayout.setHorizontalGroup(
      panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 605, Short.MAX_VALUE)
    );
    panelDatosModuloLayout.setVerticalGroup(
      panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout panelAsignarViaticosLayout = new javax.swing.GroupLayout(panelAsignarViaticos);
    panelAsignarViaticos.setLayout(panelAsignarViaticosLayout);
    panelAsignarViaticosLayout.setHorizontalGroup(
      panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addComponent(lblTitulo)
            .addGap(18, 18, 18)
            .addComponent(lblIcono))
          .addComponent(panelDatosConferencista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelDatosModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    panelAsignarViaticosLayout.setVerticalGroup(
      panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
        .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblIcono))
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(lblTitulo)))
        .addGap(18, 18, 18)
        .addComponent(panelDatosConferencista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelDatosModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(106, Short.MAX_VALUE))
    );

    menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
    menuArchivo.setText("Archivo");
    menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuArchivo);

    menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
    menuAyuda.setText("Ayuda");
    menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuAyuda);

    setJMenuBar(barraMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAsignarViaticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAsignarViaticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void btnBuscarConferencistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConferencistaActionPerformed
// TODO add your handling code here:
  int numeroCedula = 0;
  if (txtCedula.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe digitar un número de cedula para el conferencista", "Cedula Conferencista", 0);
  } else {
    try {
      numeroCedula = Integer.parseInt(txtCedula.getText().trim());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor para la cedula que\n"
              + "contenga digitos entre 0 y 9", "Valor invalido", 0);
      numeroCedula = 0;
    }
  }
  if (numeroCedula != 0) {
    try {
      conferencista = controlConferencista.BuscarConferencistaCedula(numeroCedula);
      if (conferencista != null) {
        cargarDatosConferencista(conferencista);
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se encontraron conferencistas con la cedula indicada", "Consulta sin resultados", 2);
      }
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(rootPane, "No se pudo relizar la consulta de conferencista", "Consulta faliida", 2);
    }
  }
  //Conferencista conferencista = controlConferencista.BuscarConferencistaCedula(WIDTH);
}//GEN-LAST:event_btnBuscarConferencistaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUIAsignarViaticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUIAsignarViaticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUIAsignarViaticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUIAsignarViaticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new GUIAsignarViaticos().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JButton btnBuscarConferencista;
  private javax.swing.JLabel lblApellidos;
  private javax.swing.JLabel lblCedula;
  private javax.swing.JLabel lblCelular;
  private javax.swing.JLabel lblCorreo;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JLabel lblNombres;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JPanel panelAsignarViaticos;
  private javax.swing.JPanel panelDatosConferencista;
  private javax.swing.JPanel panelDatosModulo;
  private javax.swing.JTextField txtApellidos;
  private javax.swing.JTextField txtCedula;
  private javax.swing.JTextField txtCelular;
  private javax.swing.JTextField txtCorreo;
  private javax.swing.JTextField txtNombres;
  // End of variables declaration//GEN-END:variables
}
