/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */
package Vista.Profesoral;

import Controlador.Profesoral.ControlConferencista;
import Controlador.Profesoral.ControlModulo;
import Controlador.Profesoral.ControlPrograma;
import Estructural.Conferencista;
import Estructural.Modulo;
import Estructural.Programa;
import Modelo.IServicioProfesoral;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author juanpanlo
 */
public class GUIAdicionarModulo extends javax.swing.JFrame {

  private IServicioProfesoral servicioProfesoral;
  private ControlModulo controlModulo;
  private ControlConferencista controlConferencista;
  private ControlPrograma controlPrograma;
  private Programa programa = null;
  private Conferencista conferencista = null;
  private Modulo moduloGeneral = null;
  private DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");

  /**
   * Creates new form GUIAdicionarModulo
   */
  public GUIAdicionarModulo(IServicioProfesoral servicioProfesoral) {
    initComponents();
    this.setLocationRelativeTo(null);
    this.servicioProfesoral = servicioProfesoral;
    controlConferencista = new ControlConferencista(servicioProfesoral);
    controlPrograma = new ControlPrograma(servicioProfesoral);
    controlModulo = new ControlModulo(servicioProfesoral);
    deshabilitarCampos();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelAddModulo = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblIcono = new javax.swing.JLabel();
    panelAdicionModulo = new javax.swing.JPanel();
    lblNombreModulo = new javax.swing.JLabel();
    txtNombreModulo = new javax.swing.JTextField();
    lblDuracionModulo = new javax.swing.JLabel();
    spinDuracion = new javax.swing.JSpinner();
    comboFechaInicio = new datechooser.beans.DateChooserCombo();
    lblFechaInicio = new javax.swing.JLabel();
    lblValor = new javax.swing.JLabel();
    txtValorHora = new javax.swing.JTextField();
    panelDatosConferencista = new javax.swing.JPanel();
    lblCedula = new javax.swing.JLabel();
    txtCedula = new javax.swing.JTextField();
    btnBuscarConferencista = new javax.swing.JButton();
    lblNombres = new javax.swing.JLabel();
    txtNombres = new javax.swing.JTextField();
    txtApellidos = new javax.swing.JTextField();
    lblApellidos = new javax.swing.JLabel();
    lblCorreo = new javax.swing.JLabel();
    txtCorreo = new javax.swing.JTextField();
    lblCelular = new javax.swing.JLabel();
    txtCelular = new javax.swing.JTextField();
    panelDatosPrograma = new javax.swing.JPanel();
    lblCohorteBuscar = new javax.swing.JLabel();
    txtCohorteBuscar = new javax.swing.JTextField();
    btnBuscarPrograma = new javax.swing.JButton();
    lblNombrePrograma = new javax.swing.JLabel();
    txtNombrePrograma = new javax.swing.JTextField();
    lblEstado = new javax.swing.JLabel();
    comboEstado = new javax.swing.JComboBox();
    lblValor1 = new javax.swing.JLabel();
    txtValorPrograma = new javax.swing.JTextField();
    lblParticipantes = new javax.swing.JLabel();
    spinParticipantes = new javax.swing.JSpinner();
    btnSalir = new javax.swing.JButton();
    btnActualizarConferencista = new javax.swing.JButton();
    btnAsignarViaticos = new javax.swing.JButton();
    btnAsignarTiquetes = new javax.swing.JButton();
    btnAsignarHonorarios = new javax.swing.JButton();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Adicionar MOdulo Programa");

    panelAddModulo.setBackground(new java.awt.Color(255, 255, 255));

    lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24));
    lblTitulo.setText("Adición de nuevo Modulo");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addModuleGrande.png"))); // NOI18N

    panelAdicionModulo.setBackground(new java.awt.Color(255, 255, 255));
    panelAdicionModulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Generales Modulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblNombreModulo.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNombreModulo.setText("Nombre");

    txtNombreModulo.setFont(new java.awt.Font("Calibri", 2, 13));
    txtNombreModulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblDuracionModulo.setFont(new java.awt.Font("Calibri", 2, 13));
    lblDuracionModulo.setText("Duración en horas");

    spinDuracion.setFont(new java.awt.Font("Calibri", 2, 13));
    spinDuracion.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
    spinDuracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblFechaInicio.setFont(new java.awt.Font("Calibri", 2, 13));
    lblFechaInicio.setText("Fecha de Inicio");

    lblValor.setFont(new java.awt.Font("Calibri", 2, 13));
    lblValor.setText("Valor Hora");

    txtValorHora.setFont(new java.awt.Font("Calibri", 2, 13));
    txtValorHora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    panelDatosConferencista.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosConferencista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Conferencista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblCedula.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCedula.setText("Cedula");

    txtCedula.setFont(new java.awt.Font("Calibri", 2, 13));
    txtCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    btnBuscarConferencista.setFont(new java.awt.Font("Calibri", 3, 13));
    btnBuscarConferencista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarConvenio.png"))); // NOI18N
    btnBuscarConferencista.setText("Buscar");
    btnBuscarConferencista.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarConferencistaActionPerformed(evt);
      }
    });

    lblNombres.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNombres.setText("Nombres");

    txtNombres.setFont(new java.awt.Font("Calibri", 2, 13));
    txtNombres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    txtApellidos.setFont(new java.awt.Font("Calibri", 2, 13));
    txtApellidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblApellidos.setFont(new java.awt.Font("Calibri", 2, 13));
    lblApellidos.setText("Apellidos");

    lblCorreo.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCorreo.setText("Correo Electrónico");

    txtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblCelular.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCelular.setText("Celular");

    txtCelular.setFont(new java.awt.Font("Calibri", 2, 13));
    txtCelular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    javax.swing.GroupLayout panelDatosConferencistaLayout = new javax.swing.GroupLayout(panelDatosConferencista);
    panelDatosConferencista.setLayout(panelDatosConferencistaLayout);
    panelDatosConferencistaLayout.setHorizontalGroup(
      panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
            .addComponent(lblCedula)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addComponent(btnBuscarConferencista))
          .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
            .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosConferencistaLayout.createSequentialGroup()
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosConferencistaLayout.createSequentialGroup()
                .addComponent(lblNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
                .addComponent(lblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
              .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))))
        .addContainerGap())
    );
    panelDatosConferencistaLayout.setVerticalGroup(
      panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCedula)
          .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscarConferencista))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNombres)
          .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblApellidos)
          .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCorreo)
          .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblCelular))
        .addContainerGap())
    );

    panelDatosPrograma.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosPrograma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del programa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblCohorteBuscar.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCohorteBuscar.setText("Cohorte del Programa");

    txtCohorteBuscar.setFont(new java.awt.Font("Calibri", 2, 13));
    txtCohorteBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    btnBuscarPrograma.setFont(new java.awt.Font("Calibri", 3, 13));
    btnBuscarPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editarRubro.png"))); // NOI18N
    btnBuscarPrograma.setText("Buscar Programa");
    btnBuscarPrograma.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarProgramaActionPerformed(evt);
      }
    });

    lblNombrePrograma.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNombrePrograma.setText("Nombre del Programa");

    txtNombrePrograma.setFont(new java.awt.Font("Calibri", 2, 13));
    txtNombrePrograma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblEstado.setFont(new java.awt.Font("Calibri", 2, 13));
    lblEstado.setText("Estado del Programa");

    comboEstado.setFont(new java.awt.Font("Calibri", 2, 13));
    comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vendido", "No Vendido" }));
    comboEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblValor1.setFont(new java.awt.Font("Calibri", 2, 13));
    lblValor1.setText("Valor Programa");

    txtValorPrograma.setFont(new java.awt.Font("Calibri", 2, 13));
    txtValorPrograma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblParticipantes.setFont(new java.awt.Font("Calibri", 2, 13));
    lblParticipantes.setText("Número de Participantes");

    spinParticipantes.setFont(new java.awt.Font("Calibri", 2, 13));
    spinParticipantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    spinParticipantes.setMinimumSize(new java.awt.Dimension(31, 20));

    spinParticipantes.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

    javax.swing.GroupLayout panelDatosProgramaLayout = new javax.swing.GroupLayout(panelDatosPrograma);
    panelDatosPrograma.setLayout(panelDatosProgramaLayout);
    panelDatosProgramaLayout.setHorizontalGroup(
      panelDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosProgramaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosProgramaLayout.createSequentialGroup()
            .addComponent(lblCohorteBuscar)
            .addGap(18, 18, 18)
            .addComponent(txtCohorteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnBuscarPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelDatosProgramaLayout.createSequentialGroup()
            .addComponent(lblNombrePrograma)
            .addGap(18, 18, 18)
            .addComponent(txtNombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lblEstado)
            .addGap(18, 18, 18)
            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelDatosProgramaLayout.createSequentialGroup()
            .addComponent(lblValor1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtValorPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lblParticipantes)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(spinParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(20, Short.MAX_VALUE))
    );
    panelDatosProgramaLayout.setVerticalGroup(
      panelDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosProgramaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCohorteBuscar)
          .addComponent(txtCohorteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscarPrograma))
        .addGroup(panelDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosProgramaLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(lblNombrePrograma))
          .addGroup(panelDatosProgramaLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtNombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblEstado)
              .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(18, 18, 18)
        .addGroup(panelDatosProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblValor1)
          .addComponent(txtValorPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblParticipantes)
          .addComponent(spinParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnSalir.setFont(new java.awt.Font("Calibri", 3, 13));
    btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
    btnSalir.setText("Salir");
    btnSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirActionPerformed(evt);
      }
    });

    btnActualizarConferencista.setFont(new java.awt.Font("Calibri", 3, 13));
    btnActualizarConferencista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addConferencista.png"))); // NOI18N
    btnActualizarConferencista.setText("Agregar Modulo");
    btnActualizarConferencista.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnActualizarConferencistaActionPerformed(evt);
      }
    });

    btnAsignarViaticos.setFont(new java.awt.Font("Calibri", 3, 13));
    btnAsignarViaticos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addViatico.png"))); // NOI18N
    btnAsignarViaticos.setText("Asignar Viaticos");
    btnAsignarViaticos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAsignarViaticosActionPerformed(evt);
      }
    });

    btnAsignarTiquetes.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    btnAsignarTiquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addTicket.png"))); // NOI18N
    btnAsignarTiquetes.setText("Asignar Tiquetes");
    btnAsignarTiquetes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAsignarTiquetesActionPerformed(evt);
      }
    });

    btnAsignarHonorarios.setFont(new java.awt.Font("Calibri", 3, 13));
    btnAsignarHonorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addHonorarios.png"))); // NOI18N
    btnAsignarHonorarios.setText("Asignar Honorarios");

    javax.swing.GroupLayout panelAdicionModuloLayout = new javax.swing.GroupLayout(panelAdicionModulo);
    panelAdicionModulo.setLayout(panelAdicionModuloLayout);
    panelAdicionModuloLayout.setHorizontalGroup(
      panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAdicionModuloLayout.createSequentialGroup()
        .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAdicionModuloLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(panelDatosPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(panelDatosConferencista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(panelAdicionModuloLayout.createSequentialGroup()
                .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lblNombreModulo)
                  .addComponent(lblFechaInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(panelAdicionModuloLayout.createSequentialGroup()
                    .addComponent(comboFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblValor)
                    .addGap(18, 18, 18)
                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(panelAdicionModuloLayout.createSequentialGroup()
                    .addComponent(txtNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblDuracionModulo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(spinDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addGroup(panelAdicionModuloLayout.createSequentialGroup()
                .addComponent(btnAsignarViaticos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAsignarTiquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarConferencista))))
          .addGroup(panelAdicionModuloLayout.createSequentialGroup()
            .addGap(91, 91, 91)
            .addComponent(btnAsignarHonorarios)))
        .addContainerGap())
    );
    panelAdicionModuloLayout.setVerticalGroup(
      panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAdicionModuloLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNombreModulo)
          .addComponent(txtNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblDuracionModulo)
          .addComponent(spinDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblFechaInicio)
          .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblValor)
            .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(comboFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(panelDatosConferencista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelDatosPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAdicionModuloLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnAsignarViaticos)
              .addComponent(btnAsignarTiquetes))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnAsignarHonorarios))
          .addGroup(panelAdicionModuloLayout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(panelAdicionModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnActualizarConferencista)
              .addComponent(btnSalir))))
        .addContainerGap(14, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panelAddModuloLayout = new javax.swing.GroupLayout(panelAddModulo);
    panelAddModulo.setLayout(panelAddModuloLayout);
    panelAddModuloLayout.setHorizontalGroup(
      panelAddModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAddModuloLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelAddModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelAdicionModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(panelAddModuloLayout.createSequentialGroup()
            .addComponent(lblTitulo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblIcono)))
        .addContainerGap())
    );
    panelAddModuloLayout.setVerticalGroup(
      panelAddModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAddModuloLayout.createSequentialGroup()
        .addGroup(panelAddModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAddModuloLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblIcono))
          .addGroup(panelAddModuloLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(lblTitulo)))
        .addGap(18, 18, 18)
        .addComponent(panelAdicionModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
    menuArchivo.setText("Archivo");
    menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13));
    barraMenu.add(menuArchivo);

    menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
    menuAyuda.setText("Ayuda?");
    menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13));
    barraMenu.add(menuAyuda);

    setJMenuBar(barraMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAddModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAddModulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void btnBuscarConferencistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConferencistaActionPerformed
// TODO add your handling code here:
  int numeroCedula = 0;
  if (txtCedula.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe digitar un número de cedula para el conferencista", "Cedula Conferencista", 0);
  } else {
    try {
      numeroCedula = Integer.parseInt(txtCedula.getText().trim());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor para la cedula que\n"
              + "contenga digitos entre 0 y 9", "Valor invalido", 0);
      numeroCedula = 0;
    }
  }
  if (numeroCedula != 0) {
    try {
      conferencista = controlConferencista.BuscarConferencistaCedula(numeroCedula);
      if (conferencista != null) {
        cargarDatosConferencista(conferencista);
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se encontraron conferencistas con la cedula indicada", "Consulta sin resultados", 2);
      }
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(rootPane, "No se pudo relizar la consulta de conferencista", "Consulta faliida", 2);
    }
  }
  //Conferencista conferencista = controlConferencista.BuscarConferencistaCedula(WIDTH);
}//GEN-LAST:event_btnBuscarConferencistaActionPerformed

private void btnBuscarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProgramaActionPerformed
// TODO add your handling code here:
  String cohorte = "";
  boolean controlDatos = true;
  if (txtCohorteBuscar.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Digitar una cohorte para buscar Programa", "Digite Cohorte", 0);
    controlDatos = false;
  } else {
    cohorte = txtCohorteBuscar.getText().trim();
  }
  if (controlDatos) {
    try {
      programa = controlPrograma.ConsultarPrograma(cohorte);
      if (programa != null) {
        llenarFormulario();
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se ha encontrado ningun programa con la cohorte digitada", "No se encontraron programas", 0);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}//GEN-LAST:event_btnBuscarProgramaActionPerformed

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
  // TODO add your handling code here:
  this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

private void btnActualizarConferencistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarConferencistaActionPerformed
  // TODO add your handling code here:      
  boolean controlDatos = true;
  String nombreModulo = "";
  int duracionHoras = Integer.parseInt(spinDuracion.getValue().toString());
  Date fecha = null;
  double valorHora = 0;
  if (conferencista == null || programa == null) {
    JOptionPane.showMessageDialog(rootPane, "Debe consultar un conferencista y un programa", "Consulte Conferencista y programa", 0);
    controlDatos = false;
  }
  if (txtNombreModulo.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe digitar un nombre para el Modulo", "Nombre Modulo", 0);
    controlDatos = false;
  } else {
    nombreModulo = txtNombreModulo.getText().trim();
  }
  if (txtValorHora.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor por hora del Modulo", "Valor Hora Modulo", 0);
    controlDatos = false;
  } else {
    try {
      valorHora = Integer.parseInt(txtValorHora.getText().trim());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Debe Digitar un valor de hora que solo contenga\n"
              + "digitos entre 0 y 9, sin signos ni espacios Ej: 2000", "Error valor hora Modulo", 0);
      controlDatos = false;
      System.out.println(e.getMessage());
    }
  }
  if (controlDatos) {
    try {
      fecha = formatoFecha.parse(comboFechaInicio.getText());
      Modulo modulo = new Modulo(0, nombreModulo, duracionHoras, fecha, valorHora, programa.getCohorte_programa(), conferencista.getCedula_conferencista());
      int controlAdicion = controlModulo.AgregarModuloPrograma(modulo);
      if (controlAdicion != 0) {
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Modulo Registrado Exitosamente,\n¿Desea realizar asignaciones?", "Modulo Registrado", 1);
        if (opcion == 1) {
          habilitarBotones();
        }
        modulo.setId_modulo(controlAdicion);
        moduloGeneral = modulo;
        limpiarFormulario();
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se puede crear el Modulo en este momento", "Creación fallida", 0);
      }
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "No se puede crear el Modulo en este momento", "Creación fallida", 0);
    }
  }
}//GEN-LAST:event_btnActualizarConferencistaActionPerformed

private void btnAsignarViaticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarViaticosActionPerformed
// TODO add your handling code here:
  try {
    GUIAsignarViaticos guiAsignarViaticos = new GUIAsignarViaticos(servicioProfesoral, conferencista, moduloGeneral, null);
    guiAsignarViaticos.show();
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
}//GEN-LAST:event_btnAsignarViaticosActionPerformed

private void btnAsignarTiquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTiquetesActionPerformed
// TODO add your handling code here:
  try {
    GUIAsignarTiquetes guiAsignarTiquetes = new GUIAsignarTiquetes(servicioProfesoral, conferencista, moduloGeneral, null);
    guiAsignarTiquetes.show();
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
}//GEN-LAST:event_btnAsignarTiquetesActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JButton btnActualizarConferencista;
  private javax.swing.JButton btnAsignarHonorarios;
  private javax.swing.JButton btnAsignarTiquetes;
  private javax.swing.JButton btnAsignarViaticos;
  private javax.swing.JButton btnBuscarConferencista;
  private javax.swing.JButton btnBuscarPrograma;
  private javax.swing.JButton btnSalir;
  private javax.swing.JComboBox comboEstado;
  private datechooser.beans.DateChooserCombo comboFechaInicio;
  private javax.swing.JLabel lblApellidos;
  private javax.swing.JLabel lblCedula;
  private javax.swing.JLabel lblCelular;
  private javax.swing.JLabel lblCohorteBuscar;
  private javax.swing.JLabel lblCorreo;
  private javax.swing.JLabel lblDuracionModulo;
  private javax.swing.JLabel lblEstado;
  private javax.swing.JLabel lblFechaInicio;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JLabel lblNombreModulo;
  private javax.swing.JLabel lblNombrePrograma;
  private javax.swing.JLabel lblNombres;
  private javax.swing.JLabel lblParticipantes;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JLabel lblValor;
  private javax.swing.JLabel lblValor1;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JPanel panelAddModulo;
  private javax.swing.JPanel panelAdicionModulo;
  private javax.swing.JPanel panelDatosConferencista;
  private javax.swing.JPanel panelDatosPrograma;
  private javax.swing.JSpinner spinDuracion;
  private javax.swing.JSpinner spinParticipantes;
  private javax.swing.JTextField txtApellidos;
  private javax.swing.JTextField txtCedula;
  private javax.swing.JTextField txtCelular;
  private javax.swing.JTextField txtCohorteBuscar;
  private javax.swing.JTextField txtCorreo;
  private javax.swing.JTextField txtNombreModulo;
  private javax.swing.JTextField txtNombrePrograma;
  private javax.swing.JTextField txtNombres;
  private javax.swing.JTextField txtValorHora;
  private javax.swing.JTextField txtValorPrograma;
  // End of variables declaration//GEN-END:variables

  private void cargarDatosConferencista(Conferencista conferencista) {
    txtNombres.setText(conferencista.getNombres_conferencista());
    txtApellidos.setText(conferencista.getApellidos_conferencista());
    txtCelular.setText(conferencista.getCelular_conferencista());
    txtCorreo.setText(conferencista.getCorreo_electronico_conferencista());
  }

  private void llenarFormulario() {
    txtNombrePrograma.setText(programa.getNombre_programa());
    txtValorPrograma.setText(String.valueOf(programa.getValor()));
    comboEstado.setSelectedItem(programa.getEstado());
    spinParticipantes.setValue(programa.getParticipantes());
  }

  private void deshabilitarCampos() {
    txtNombres.setEditable(false);
    txtApellidos.setEditable(false);
    txtCorreo.setEditable(false);
    txtCelular.setEditable(false);
    txtNombrePrograma.setEditable(false);
    txtValorPrograma.setEditable(false);
    comboEstado.setEditable(false);
    spinParticipantes.setEnabled(false);
    btnAsignarHonorarios.setVisible(false);
    btnAsignarTiquetes.setVisible(false);
    btnAsignarViaticos.setVisible(false);
  }

  private void limpiarFormulario() {
    txtNombreModulo.setText("");
    spinDuracion.setValue(1);
    txtCedula.setText("");
    txtCohorteBuscar.setText("");
    txtValorPrograma.setText("");
    txtNombres.setText("");
    txtApellidos.setText("");
    txtCelular.setText("");
    txtCorreo.setText("");
    txtNombrePrograma.setText("");
    txtValorHora.setText("");
    comboEstado.setSelectedItem("Vendido");
    spinParticipantes.setValue(1);
    programa = null;
    //conferencista = null;
    btnAsignarHonorarios.setVisible(true);
    btnAsignarTiquetes.setVisible(true);
    btnAsignarViaticos.setVisible(true);
  }

  private void habilitarBotones() {
    btnAsignarHonorarios.setVisible(true);
    btnAsignarTiquetes.setVisible(true);
    btnAsignarViaticos.setVisible(true);
  }
}
