/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIAsignarTiquetes.java
 *
 * Created on 12/11/2012, 08:21:44 PM
 */
package Vista.Profesoral;

import Controlador.Profesoral.ControlAsignaciones;
import Controlador.Profesoral.ControlConferencista;
import Controlador.Profesoral.ControlModulo;
import Controlador.Profesoral.ControlPrograma;
import Estructural.Asignacion_tiquete;
import Estructural.Asignacion_viaticos;
import Estructural.Conferencista;
import Estructural.Modulo;
import Estructural.Programa;
import Modelo.IServicioProfesoral;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Kmilo
 */
public class GUIAsignarTiquetes extends javax.swing.JFrame {

  private IServicioProfesoral servicioProfesoral;
  private ControlModulo controlModulo;
  private ControlConferencista controlConferencista;
  private ControlPrograma controlPrograma;
  private ControlAsignaciones controlAsignaciones;
  private Programa programa = null;
  private Conferencista conferencista = null;
  public Modulo modulo;
  private DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");
  private GUIBuscarModulo guiBuscarModulo = null;

  /** Creates new form GUIAsignarTiquetes */
  public GUIAsignarTiquetes(IServicioProfesoral servicioProfesoral, Conferencista conferencista,
          Modulo modulo, GUIBuscarModulo guiBuscarModulo) throws RemoteException {
    initComponents();
    this.setLocationRelativeTo(null);
    this.servicioProfesoral = servicioProfesoral;
    controlConferencista = new ControlConferencista(servicioProfesoral);
    controlPrograma = new ControlPrograma(servicioProfesoral);
    controlAsignaciones = new ControlAsignaciones(servicioProfesoral);
    controlModulo = new ControlModulo(servicioProfesoral);
    this.conferencista = conferencista;
    this.modulo = modulo;
    deshabilitarCampos();
    cargarModulo();
    cargarDatosConferencista(conferencista);
    this.guiBuscarModulo = guiBuscarModulo;
    if (this.guiBuscarModulo != null) {
      this.guiBuscarModulo.dispose();
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelAsignarTiquetes = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblIcono = new javax.swing.JLabel();
    panelDatosAsignacion = new javax.swing.JPanel();
    lblFechaSolicitud = new javax.swing.JLabel();
    comboFechaSolicitud = new datechooser.beans.DateChooserCombo();
    lblCiudadOrigen = new javax.swing.JLabel();
    txtCiudadOrigen = new javax.swing.JTextField();
    lblCiudadDestino = new javax.swing.JLabel();
    txtCiudadDestino = new javax.swing.JTextField();
    lblAerolinea = new javax.swing.JLabel();
    txtAerolinea = new javax.swing.JTextField();
    lblFechaSalida = new javax.swing.JLabel();
    comboFechaSalida = new datechooser.beans.DateChooserCombo();
    lblFechaRegreso = new javax.swing.JLabel();
    comboFechaRegreso = new datechooser.beans.DateChooserCombo();
    panelDatosConferencista = new javax.swing.JPanel();
    lblCedula = new javax.swing.JLabel();
    txtCedula = new javax.swing.JTextField();
    btnBuscarConferencista = new javax.swing.JButton();
    lblNombres = new javax.swing.JLabel();
    txtNombres = new javax.swing.JTextField();
    txtApellidos = new javax.swing.JTextField();
    lblApellidos = new javax.swing.JLabel();
    lblCorreo = new javax.swing.JLabel();
    txtCorreo = new javax.swing.JTextField();
    lblCelular = new javax.swing.JLabel();
    txtCelular = new javax.swing.JTextField();
    panelDatosModulo = new javax.swing.JPanel();
    lblNombreModulo = new javax.swing.JLabel();
    txtNombreModulo = new javax.swing.JTextField();
    lblDuracionModulo = new javax.swing.JLabel();
    spinDuracion = new javax.swing.JSpinner();
    lblFechaInicio = new javax.swing.JLabel();
    comboFechaInicio = new datechooser.beans.DateChooserCombo();
    lblValor = new javax.swing.JLabel();
    txtValorHora = new javax.swing.JTextField();
    btnBuscarModulo = new javax.swing.JButton();
    panelInfoPrograma = new javax.swing.JPanel();
    lblCohorte = new javax.swing.JLabel();
    txtCohorte = new javax.swing.JTextField();
    lblNombrePrograma = new javax.swing.JLabel();
    txtNombre = new javax.swing.JTextField();
    lblFecha = new javax.swing.JLabel();
    comboFecha = new datechooser.beans.DateChooserCombo();
    lblValor1 = new javax.swing.JLabel();
    txtValor = new javax.swing.JTextField();
    lblParticipantes = new javax.swing.JLabel();
    spinParticipantes = new javax.swing.JSpinner();
    lblEstado = new javax.swing.JLabel();
    comboEstado = new javax.swing.JComboBox();
    btnAsignar = new javax.swing.JButton();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Asignación de Tiquetes");

    panelAsignarTiquetes.setBackground(new java.awt.Color(255, 255, 255));

    lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
    lblTitulo.setText("Asignación de Tiquetes");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addTicketGrande.png"))); // NOI18N

    panelDatosAsignacion.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosAsignacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Asignación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblFechaSolicitud.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblFechaSolicitud.setText("Fecha de Solicitud");

    lblCiudadOrigen.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblCiudadOrigen.setText("Ciudad de Origen");

    txtCiudadOrigen.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N

    lblCiudadDestino.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblCiudadDestino.setText("Ciudad de Destino");

    txtCiudadDestino.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N

    lblAerolinea.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblAerolinea.setText("Aerolinea");

    txtAerolinea.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N

    lblFechaSalida.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblFechaSalida.setText("Fecha de Salida");

    lblFechaRegreso.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblFechaRegreso.setText("Fecha de Regreso");

    javax.swing.GroupLayout panelDatosAsignacionLayout = new javax.swing.GroupLayout(panelDatosAsignacion);
    panelDatosAsignacion.setLayout(panelDatosAsignacionLayout);
    panelDatosAsignacionLayout.setHorizontalGroup(
      panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
            .addComponent(lblFechaSolicitud)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(comboFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
            .addComponent(lblCiudadOrigen)
            .addGap(10, 10, 10)
            .addComponent(txtCiudadOrigen)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lblCiudadDestino)
          .addComponent(lblFechaSalida))
        .addGap(10, 10, 10)
        .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(txtCiudadDestino)
          .addComponent(comboFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(12, 12, 12)
        .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosAsignacionLayout.createSequentialGroup()
            .addComponent(lblAerolinea)
            .addGap(10, 10, 10)
            .addComponent(txtAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
            .addComponent(lblFechaRegreso)
            .addGap(10, 10, 10)
            .addComponent(comboFechaRegreso, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
        .addContainerGap())
    );
    panelDatosAsignacionLayout.setVerticalGroup(
      panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblFechaSolicitud)
          .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
              .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(lblFechaSalida)
                .addComponent(comboFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblCiudadDestino)))
            .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
              .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(comboFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(lblFechaRegreso)
                  .addComponent(comboFechaRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblCiudadOrigen)
                .addComponent(txtAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblAerolinea)))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelDatosConferencista.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosConferencista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Conferencista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblCedula.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCedula.setText("Cedula");

    txtCedula.setFont(new java.awt.Font("Calibri", 2, 13));
    txtCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    btnBuscarConferencista.setFont(new java.awt.Font("Calibri", 3, 13));
    btnBuscarConferencista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarConvenio.png"))); // NOI18N
    btnBuscarConferencista.setText("Buscar");
    btnBuscarConferencista.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarConferencistaActionPerformed(evt);
      }
    });

    lblNombres.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNombres.setText("Nombres");

    txtNombres.setFont(new java.awt.Font("Calibri", 2, 13));
    txtNombres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    txtApellidos.setFont(new java.awt.Font("Calibri", 2, 13));
    txtApellidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblApellidos.setFont(new java.awt.Font("Calibri", 2, 13));
    lblApellidos.setText("Apellidos");

    lblCorreo.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCorreo.setText("Correo Electrónico");

    txtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblCelular.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCelular.setText("Celular");

    txtCelular.setFont(new java.awt.Font("Calibri", 2, 13));
    txtCelular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    javax.swing.GroupLayout panelDatosConferencistaLayout = new javax.swing.GroupLayout(panelDatosConferencista);
    panelDatosConferencista.setLayout(panelDatosConferencistaLayout);
    panelDatosConferencistaLayout.setHorizontalGroup(
      panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
            .addComponent(lblCedula)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addComponent(btnBuscarConferencista))
          .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
            .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosConferencistaLayout.createSequentialGroup()
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosConferencistaLayout.createSequentialGroup()
                .addComponent(lblNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
                .addComponent(lblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
              .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)))))
        .addContainerGap())
    );
    panelDatosConferencistaLayout.setVerticalGroup(
      panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosConferencistaLayout.createSequentialGroup()
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCedula)
          .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscarConferencista))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNombres)
          .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblApellidos)
          .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
        .addGroup(panelDatosConferencistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCorreo)
          .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblCelular))
        .addContainerGap())
    );

    panelDatosModulo.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosModulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Modulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblNombreModulo.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNombreModulo.setText("Nombre");

    txtNombreModulo.setFont(new java.awt.Font("Calibri", 2, 13));
    txtNombreModulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblDuracionModulo.setFont(new java.awt.Font("Calibri", 2, 13));
    lblDuracionModulo.setText("Duración en horas");

    spinDuracion.setFont(new java.awt.Font("Calibri", 2, 13));
    spinDuracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblFechaInicio.setFont(new java.awt.Font("Calibri", 2, 13));
    lblFechaInicio.setText("Fecha de Inicio");

    lblValor.setFont(new java.awt.Font("Calibri", 2, 13));
    lblValor.setText("Valor Hora");

    txtValorHora.setFont(new java.awt.Font("Calibri", 2, 13));
    txtValorHora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    btnBuscarModulo.setFont(new java.awt.Font("Calibri", 3, 13));
    btnBuscarModulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarConvenio.png"))); // NOI18N
    btnBuscarModulo.setText("Buscar Modulo");
    btnBuscarModulo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarModuloActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelDatosModuloLayout = new javax.swing.GroupLayout(panelDatosModulo);
    panelDatosModulo.setLayout(panelDatosModuloLayout);
    panelDatosModuloLayout.setHorizontalGroup(
      panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosModuloLayout.createSequentialGroup()
        .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosModuloLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblNombreModulo)
              .addComponent(lblFechaInicio))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelDatosModuloLayout.createSequentialGroup()
                .addComponent(comboFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValor)
                .addGap(18, 18, 18)
                .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(panelDatosModuloLayout.createSequentialGroup()
                .addComponent(txtNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDuracionModulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(panelDatosModuloLayout.createSequentialGroup()
            .addGap(297, 297, 297)
            .addComponent(btnBuscarModulo)))
        .addContainerGap(136, Short.MAX_VALUE))
    );
    panelDatosModuloLayout.setVerticalGroup(
      panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosModuloLayout.createSequentialGroup()
        .addComponent(btnBuscarModulo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
        .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNombreModulo)
          .addComponent(txtNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblDuracionModulo)
          .addComponent(spinDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblFechaInicio)
          .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblValor)
            .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(comboFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    panelInfoPrograma.setBackground(new java.awt.Color(255, 255, 255));
    panelInfoPrograma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Programa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblCohorte.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCohorte.setText("Cohorte del Programa");

    txtCohorte.setFont(new java.awt.Font("Calibri", 2, 13));
    txtCohorte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblNombrePrograma.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNombrePrograma.setText("Nombre del Programa");

    txtNombre.setFont(new java.awt.Font("Calibri", 2, 13));
    txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblFecha.setFont(new java.awt.Font("Calibri", 2, 13));
    lblFecha.setText("Fecha Inicio");

    lblValor1.setFont(new java.awt.Font("Calibri", 2, 13));
    lblValor1.setText("Valor Programa");

    txtValor.setFont(new java.awt.Font("Calibri", 2, 13));
    txtValor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    lblParticipantes.setFont(new java.awt.Font("Calibri", 2, 13));
    lblParticipantes.setText("Número de Participantes");

    spinParticipantes.setFont(new java.awt.Font("Calibri", 2, 13));
    spinParticipantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    spinParticipantes.setMinimumSize(new java.awt.Dimension(31, 20));

    lblEstado.setFont(new java.awt.Font("Calibri", 2, 13));
    lblEstado.setText("Estado del Programa");

    comboEstado.setFont(new java.awt.Font("Calibri", 2, 13));
    comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vendido", "No Vendido" }));
    comboEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    spinParticipantes.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

    javax.swing.GroupLayout panelInfoProgramaLayout = new javax.swing.GroupLayout(panelInfoPrograma);
    panelInfoPrograma.setLayout(panelInfoProgramaLayout);
    panelInfoProgramaLayout.setHorizontalGroup(
      panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelInfoProgramaLayout.createSequentialGroup()
        .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelInfoProgramaLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelInfoProgramaLayout.createSequentialGroup()
                .addComponent(lblCohorte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(txtCohorte, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(panelInfoProgramaLayout.createSequentialGroup()
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblValor1)
              .addComponent(lblNombrePrograma))
            .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(panelInfoProgramaLayout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(panelInfoProgramaLayout.createSequentialGroup()
                .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(panelInfoProgramaLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblParticipantes)
                    .addGap(35, 35, 35))
                  .addGroup(panelInfoProgramaLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(174, 174, 174)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(panelInfoProgramaLayout.createSequentialGroup()
            .addGap(201, 201, 201)
            .addComponent(lblEstado)
            .addGap(29, 29, 29)
            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    panelInfoProgramaLayout.setVerticalGroup(
      panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelInfoProgramaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(panelInfoProgramaLayout.createSequentialGroup()
            .addComponent(lblNombrePrograma)
            .addGap(18, 18, 18)
            .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lblValor1)
              .addComponent(lblParticipantes)
              .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(spinParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(panelInfoProgramaLayout.createSequentialGroup()
            .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lblCohorte)
              .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtCohorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(lblFecha)
              .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(18, 18, 18)
        .addGroup(panelInfoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblEstado)
          .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnAsignar.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    btnAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addTicket.png"))); // NOI18N
    btnAsignar.setText("Asignar");
    btnAsignar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAsignarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelAsignarTiquetesLayout = new javax.swing.GroupLayout(panelAsignarTiquetes);
    panelAsignarTiquetes.setLayout(panelAsignarTiquetesLayout);
    panelAsignarTiquetesLayout.setHorizontalGroup(
      panelAsignarTiquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsignarTiquetesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelAsignarTiquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsignarTiquetesLayout.createSequentialGroup()
            .addGroup(panelAsignarTiquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(panelDatosAsignacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(panelDatosModulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(panelDatosConferencista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(panelInfoPrograma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
          .addGroup(panelAsignarTiquetesLayout.createSequentialGroup()
            .addComponent(lblTitulo)
            .addGap(18, 18, 18)
            .addComponent(lblIcono)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
            .addComponent(btnAsignar)
            .addGap(27, 27, 27))))
    );
    panelAsignarTiquetesLayout.setVerticalGroup(
      panelAsignarTiquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAsignarTiquetesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelAsignarTiquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(panelAsignarTiquetesLayout.createSequentialGroup()
            .addGroup(panelAsignarTiquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelAsignarTiquetesLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTitulo))
              .addComponent(lblIcono))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
          .addComponent(btnAsignar))
        .addComponent(panelDatosAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelDatosConferencista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelDatosModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelInfoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
    menuArchivo.setText("Archivo");
    menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuArchivo);

    menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
    menuAyuda.setText("Ayuda");
    menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuAyuda);

    setJMenuBar(barraMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAsignarTiquetes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAsignarTiquetes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
// TODO add your handling code here:
  boolean controlDatos = true;
  Date fechaSolicitud = null;
  Date fechaSalida = null;
  Date fechaRegreso = null;
  String ciudadOrigen = "";
  String ciudadDestino = "";
  String aerolinea = "";
  if (conferencista == null || modulo == null || programa == null) {
    JOptionPane.showMessageDialog(rootPane, "Debe buscar un conferencista y un modulo\npara Crear la asignación", "Error", 2);
    controlDatos = false;
  }
  if (txtCiudadOrigen.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Ingresar una Ciudad de Origen para la generación de Tiquetes", "Ciudad de Origen", 0);
    controlDatos = false;
  } else {
    ciudadOrigen = txtCiudadOrigen.getText().trim();
  }
  if (txtCiudadDestino.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Ingresar una Ciudad de Destino para la generación de Tiquetes", "Ciudad de Destino", 0);
    controlDatos = false;
  } else {
    ciudadDestino = txtCiudadDestino.getText().trim();
  }
  if (txtAerolinea.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Ingresar una Aerolinea para la generación de Tiquetes", "Aerolinea", 0);
    controlDatos = false;
  } else {
    aerolinea = txtAerolinea.getText().trim();
  }
  if (controlDatos) {
    try {
      fechaSolicitud = formatoFecha.parse(comboFechaSolicitud.getText());
      fechaSalida = formatoFecha.parse(comboFechaSalida.getText());
      fechaRegreso = formatoFecha.parse(comboFechaRegreso.getText());
      Asignacion_tiquete asignacionTiquete = new Asignacion_tiquete(0, fechaSolicitud, fechaSalida,fechaRegreso, ciudadOrigen, ciudadDestino, aerolinea, modulo.getId_modulo());
      boolean controlAsignacion = controlAsignaciones.AgregarAsignacionViaticos(asignacionViaticos);
      if (controlAsignacion) {
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Se han asignado los viaticos de manera correcta\n"
                + "¿Desea generar el imprimible de los mismos?", "Asignación creada", 1);
        if (opcion == 0) {
          //Codigo para generar archivo y muestra notificacion
        } else {
          limpiarDatos();
        }
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se puede crear la asignación de viaticos", "Creación fallida", 0);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}//GEN-LAST:event_btnAsignarActionPerformed

private void btnBuscarConferencistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConferencistaActionPerformed
// TODO add your handling code here:
  int numeroCedula = 0;
  if (txtCedula.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe digitar un número de cedula para el conferencista", "Cedula Conferencista", 0);
  } else {
    try {
      numeroCedula = Integer.parseInt(txtCedula.getText().trim());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor para la cedula que\n"
              + "contenga digitos entre 0 y 9", "Valor invalido", 0);
      numeroCedula = 0;
    }
  }
  if (numeroCedula != 0) {
    try {
      conferencista = controlConferencista.BuscarConferencistaCedula(numeroCedula);
      if (conferencista != null) {
        cargarDatosConferencista(conferencista);
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se encontraron conferencistas con la cedula indicada", "Consulta sin resultados", 2);
      }
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(rootPane, "No se pudo relizar la consulta de conferencista", "Consulta faliida", 2);
    }
  }
  //Conferencista conferencista = controlConferencista.BuscarConferencistaCedula(WIDTH);
}//GEN-LAST:event_btnBuscarConferencistaActionPerformed

private void btnBuscarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModuloActionPerformed
// TODO add your handling code here:
  try {
    GUIBuscarModulo guiBuscarModuloBtn = new GUIBuscarModulo(servicioProfesoral, null, this);
    guiBuscarModuloBtn.show();
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
}//GEN-LAST:event_btnBuscarModuloActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JButton btnAsignar;
  private javax.swing.JButton btnBuscarConferencista;
  private javax.swing.JButton btnBuscarModulo;
  private javax.swing.JComboBox comboEstado;
  private datechooser.beans.DateChooserCombo comboFecha;
  private datechooser.beans.DateChooserCombo comboFechaInicio;
  private datechooser.beans.DateChooserCombo comboFechaRegreso;
  private datechooser.beans.DateChooserCombo comboFechaSalida;
  private datechooser.beans.DateChooserCombo comboFechaSolicitud;
  private javax.swing.JLabel lblAerolinea;
  private javax.swing.JLabel lblApellidos;
  private javax.swing.JLabel lblCedula;
  private javax.swing.JLabel lblCelular;
  private javax.swing.JLabel lblCiudadDestino;
  private javax.swing.JLabel lblCiudadOrigen;
  private javax.swing.JLabel lblCohorte;
  private javax.swing.JLabel lblCorreo;
  private javax.swing.JLabel lblDuracionModulo;
  private javax.swing.JLabel lblEstado;
  private javax.swing.JLabel lblFecha;
  private javax.swing.JLabel lblFechaInicio;
  private javax.swing.JLabel lblFechaRegreso;
  private javax.swing.JLabel lblFechaSalida;
  private javax.swing.JLabel lblFechaSolicitud;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JLabel lblNombreModulo;
  private javax.swing.JLabel lblNombrePrograma;
  private javax.swing.JLabel lblNombres;
  private javax.swing.JLabel lblParticipantes;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JLabel lblValor;
  private javax.swing.JLabel lblValor1;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JPanel panelAsignarTiquetes;
  private javax.swing.JPanel panelDatosAsignacion;
  private javax.swing.JPanel panelDatosConferencista;
  private javax.swing.JPanel panelDatosModulo;
  private javax.swing.JPanel panelInfoPrograma;
  private javax.swing.JSpinner spinDuracion;
  private javax.swing.JSpinner spinParticipantes;
  private javax.swing.JTextField txtAerolinea;
  private javax.swing.JTextField txtApellidos;
  private javax.swing.JTextField txtCedula;
  private javax.swing.JTextField txtCelular;
  private javax.swing.JTextField txtCiudadDestino;
  private javax.swing.JTextField txtCiudadOrigen;
  private javax.swing.JTextField txtCohorte;
  private javax.swing.JTextField txtCorreo;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JTextField txtNombreModulo;
  private javax.swing.JTextField txtNombres;
  private javax.swing.JTextField txtValor;
  private javax.swing.JTextField txtValorHora;
  // End of variables declaration//GEN-END:variables

  private void cargarDatosConferencista(Conferencista conferencista) {
    if (conferencista != null) {
      txtCedula.setText(String.valueOf(conferencista.getCedula_conferencista()));
      txtNombres.setText(conferencista.getNombres_conferencista());
      txtApellidos.setText(conferencista.getApellidos_conferencista());
      txtCelular.setText(conferencista.getCelular_conferencista());
      txtCorreo.setText(conferencista.getCorreo_electronico_conferencista());
    }
  }

  private void deshabilitarCampos() {
    txtNombres.setEditable(false);
    txtApellidos.setEditable(false);
    txtCorreo.setEditable(false);
    txtCelular.setEditable(false);
  }

  public void cargarModulo() throws RemoteException {
    if (modulo != null) {
      programa = controlPrograma.ConsultarPrograma(modulo.getCohorte_programa());
      if (programa != null) {
        txtCohorte.setText(programa.getCohorte_programa());
        txtNombre.setText(programa.getNombre_programa());
        comboFecha.setText(formatoFecha.format(programa.getFecha_inicio_programa()));
        txtValor.setText(String.valueOf(programa.getValor()));
        spinDuracion.setValue(programa.getParticipantes());
        comboEstado.setSelectedItem(programa.getEstado());
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se Encontro el Programa para esta asignación", "No existe Programa", 2);
      }
      txtNombreModulo.setText(modulo.getNombre_modulo());
      spinDuracion.setValue(modulo.getDuracion_modulo_horas());
      comboFechaInicio.setText(formatoFecha.format(modulo.getFecha_inicio_modulo()));
      txtValorHora.setText(String.valueOf(modulo.getValor_hora()));
      btnBuscarModulo.setEnabled(false);
    }
  }

  private void limpiarDatos() {
    programa = null;
    conferencista = null;
    modulo = null;
    txtCohorte.setText("");
    txtNombre.setText("");
    comboFecha.setText("");
    txtValor.setText("");
    spinDuracion.setValue("");
    comboEstado.setSelectedItem("");
    txtNombres.setText("");
    txtApellidos.setText("");
    txtCorreo.setText("");
    txtCelular.setText("");
    txtNombreModulo.setText("");
    spinDuracion.setValue("");
    comboFechaInicio.setText("");
    txtValorHora.setText("");
  }
}
