/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIBuscarModulo.java
 *
 * Created on 12/11/2012, 03:40:57 PM
 */
package Vista.Profesoral;

import Controlador.Profesoral.ControlModulo;
import Estructural.Modulo;
import Modelo.IServicioProfesoral;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kmilo
 */
public class GUIBuscarModulo extends javax.swing.JFrame {

  private IServicioProfesoral servicioProfesoral;
  private ControlModulo controlModulo;
  private GUIAsignarViaticos guiAsignarViaticos;
  private GUIAsignarTiquetes guiAsignarTiquetes;
  private ArrayList<Modulo> modulos = null;

  /** Creates new form GUIBuscarModulo */
  public GUIBuscarModulo(IServicioProfesoral servicioProfesoral, GUIAsignarViaticos guiAsignarViaticos,
          GUIAsignarTiquetes guiAsignarTiquetes) {
    initComponents();
    this.setLocationRelativeTo(null);
    controlModulo = new ControlModulo(servicioProfesoral);
    this.servicioProfesoral = servicioProfesoral;
    this.guiAsignarViaticos = guiAsignarViaticos;
    this.guiAsignarTiquetes = guiAsignarTiquetes;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelBuscarModulo = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblIcono = new javax.swing.JLabel();
    panelDatosBusqueda = new javax.swing.JPanel();
    lblCohorte = new javax.swing.JLabel();
    txtCohorte = new javax.swing.JTextField();
    btnBuscarPrograma = new javax.swing.JButton();
    panelResultadosBusqueda = new javax.swing.JPanel();
    scrollResultados = new javax.swing.JScrollPane();
    tablaResultadosBusqueda = new javax.swing.JTable();
    btnSalir = new javax.swing.JButton();
    btnAsignarViatico = new javax.swing.JButton();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Busqueda de Modulos por Programa");

    panelBuscarModulo.setBackground(new java.awt.Color(255, 255, 255));

    lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
    lblTitulo.setText("Busqueda de Modulos por Programa");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarModuloGrande.png"))); // NOI18N

    panelDatosBusqueda.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblCohorte.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblCohorte.setText("Cohorte del Programa");

    txtCohorte.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    txtCohorte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    btnBuscarPrograma.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    btnBuscarPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarModulo.png"))); // NOI18N
    btnBuscarPrograma.setText("Buscar");
    btnBuscarPrograma.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarProgramaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelDatosBusquedaLayout = new javax.swing.GroupLayout(panelDatosBusqueda);
    panelDatosBusqueda.setLayout(panelDatosBusquedaLayout);
    panelDatosBusquedaLayout.setHorizontalGroup(
      panelDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosBusquedaLayout.createSequentialGroup()
        .addGap(113, 113, 113)
        .addComponent(lblCohorte)
        .addGap(21, 21, 21)
        .addComponent(txtCohorte, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnBuscarPrograma)
        .addContainerGap(276, Short.MAX_VALUE))
    );
    panelDatosBusquedaLayout.setVerticalGroup(
      panelDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosBusquedaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCohorte)
          .addComponent(btnBuscarPrograma)
          .addComponent(txtCohorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelResultadosBusqueda.setBackground(new java.awt.Color(255, 255, 255));
    panelResultadosBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados de la Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    tablaResultadosBusqueda.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Nombre Modulo", "Duración Modulo (Horas)", "Fecha de Inicio", "Valor Hora", "Cohorte Programa", "Cedula Conferencista"
      }
    ));
    scrollResultados.setViewportView(tablaResultadosBusqueda);

    javax.swing.GroupLayout panelResultadosBusquedaLayout = new javax.swing.GroupLayout(panelResultadosBusqueda);
    panelResultadosBusqueda.setLayout(panelResultadosBusquedaLayout);
    panelResultadosBusquedaLayout.setHorizontalGroup(
      panelResultadosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelResultadosBusquedaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        .addContainerGap())
    );
    panelResultadosBusquedaLayout.setVerticalGroup(
      panelResultadosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelResultadosBusquedaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        .addContainerGap())
    );

    btnSalir.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
    btnSalir.setText("Salir");
    btnSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirActionPerformed(evt);
      }
    });

    btnAsignarViatico.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
    btnAsignarViatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addViatico.png"))); // NOI18N
    btnAsignarViatico.setText("Asignar Viaticos");
    btnAsignarViatico.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAsignarViaticoActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelBuscarModuloLayout = new javax.swing.GroupLayout(panelBuscarModulo);
    panelBuscarModulo.setLayout(panelBuscarModuloLayout);
    panelBuscarModuloLayout.setHorizontalGroup(
      panelBuscarModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelBuscarModuloLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelBuscarModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelResultadosBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelDatosBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(panelBuscarModuloLayout.createSequentialGroup()
            .addComponent(lblTitulo)
            .addGap(10, 10, 10)
            .addComponent(lblIcono))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarModuloLayout.createSequentialGroup()
            .addComponent(btnAsignarViatico, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(35, 35, 35)
            .addComponent(btnSalir)))
        .addContainerGap())
    );
    panelBuscarModuloLayout.setVerticalGroup(
      panelBuscarModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelBuscarModuloLayout.createSequentialGroup()
        .addGroup(panelBuscarModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelBuscarModuloLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblIcono))
          .addGroup(panelBuscarModuloLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(lblTitulo)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelDatosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelResultadosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelBuscarModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnSalir)
          .addComponent(btnAsignarViatico))
        .addContainerGap(12, Short.MAX_VALUE))
    );

    menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
    menuArchivo.setText("Archivo");
    menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuArchivo);

    menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
    menuAyuda.setText("Ayuda");
    menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuAyuda);

    setJMenuBar(barraMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelBuscarModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelBuscarModulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void btnBuscarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProgramaActionPerformed
// TODO add your handling code here:
  String cohorte = "";
  if (txtCohorte.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe digitar una cohorte de Programa para buscar", "Digite cohorte del programa", 0);
  } else {
    cohorte = txtCohorte.getText().trim();
    try {
      modulos = controlModulo.BuscarModuloPrograma(cohorte);
      if (modulos.isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "No se encontraton modulos vinculados al programa", "No hay resultados que mostrar", 0);
        limpiarTablaResultados();
      } else {
        cargarModulos(modulos);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}//GEN-LAST:event_btnBuscarProgramaActionPerformed

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
  this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

private void btnAsignarViaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarViaticoActionPerformed
// TODO add your handling code here:
  if (modulos.isEmpty()) {
    JOptionPane.showMessageDialog(rootPane, "Debe realizar una consulta por cohorte de Programa", "Debe Buscar Primero", 0);
  } else {
    int filaSeleccionada = tablaResultadosBusqueda.getSelectedRow();
    if (filaSeleccionada != -1) {
      if (guiAsignarViaticos != null) {
        try {
          guiAsignarViaticos.modulo = modulos.get(filaSeleccionada);
          guiAsignarViaticos.cargarModulo();
          this.dispose();
        } catch (RemoteException ex) {
          System.out.println(ex.getMessage());
        }
      } else {
        try {
          GUIAsignarViaticos guiAsignarViaticosLocal = new GUIAsignarViaticos(servicioProfesoral, null, modulos.get(filaSeleccionada), this);
          guiAsignarViaticosLocal.show();
        } catch (Exception e) {
          System.out.println(e.getMessage());
        }
      }
    } else {
      JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un Modulo para realizar la asignación", "Seleccione Modulo del Listado", 0);
    }
  }
}//GEN-LAST:event_btnAsignarViaticoActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JButton btnAsignarViatico;
  private javax.swing.JButton btnBuscarPrograma;
  private javax.swing.JButton btnSalir;
  private javax.swing.JLabel lblCohorte;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JPanel panelBuscarModulo;
  private javax.swing.JPanel panelDatosBusqueda;
  private javax.swing.JPanel panelResultadosBusqueda;
  private javax.swing.JScrollPane scrollResultados;
  private javax.swing.JTable tablaResultadosBusqueda;
  private javax.swing.JTextField txtCohorte;
  // End of variables declaration//GEN-END:variables

  private void cargarModulos(ArrayList<Modulo> modulos) {
    int fila = 0;
    for (int i = 0; i < modulos.size(); i++) {
      if (tablaResultadosBusqueda.getRowCount() == fila) {
        DefaultTableModel tablaTemp = (DefaultTableModel) tablaResultadosBusqueda.getModel();
        Object nuevo[] = {null, null, null, null, null, null};
        tablaTemp.addRow(nuevo);
      }
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getNombre_modulo(), i, 0);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getDuracion_modulo_horas(), i, 1);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getFecha_inicio_modulo(), i, 2);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getValor_hora(), i, 3);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getCohorte_programa(), i, 4);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getCedula_conferencista(), i, 5);
      fila++;
    }
    if (tablaResultadosBusqueda.getRowCount() > fila) {
      DefaultTableModel tablaTemp = (DefaultTableModel) tablaResultadosBusqueda.getModel();
      tablaTemp.removeRow(fila);
    }
  }

  private void limpiarTablaResultados() {
    for (int i = 0; i < tablaResultadosBusqueda.getRowCount(); i++) {
      tablaResultadosBusqueda.setValueAt("", i, 0);
      tablaResultadosBusqueda.setValueAt("", i, 1);
      tablaResultadosBusqueda.setValueAt("", i, 2);
      tablaResultadosBusqueda.setValueAt("", i, 3);
      tablaResultadosBusqueda.setValueAt("", i, 4);
      tablaResultadosBusqueda.setValueAt("", i, 5);
    }
  }
}
