/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIEditarAsignacionHonorarios.java
 *
 * Created on 13/11/2012, 01:08:38 PM
 */
package Vista.Profesoral;

import Controlador.Profesoral.ControlAsignaciones;
import Controlador.Profesoral.ControlConferencista;
import Controlador.Profesoral.ControlModulo;
import Controlador.Profesoral.ControlPrograma;
import Estructural.Asignacion_honorarios;
import Estructural.Conferencista;
import Estructural.Modulo;
import Estructural.Programa;
import Modelo.IServicioProfesoral;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kmilo
 */
public class GUIEditarAsignacionHonorarios extends javax.swing.JFrame {

  private IServicioProfesoral servicioProfesoral;
  private ControlModulo controlModulo;
  private ControlConferencista controlConferencista;
  private ControlPrograma controlPrograma;
  private ControlAsignaciones controlAsignaciones;
  private Programa programa = null;
  private Conferencista conferencista = null;
  public Modulo modulo;
  private DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");
  private ArrayList<Modulo> modulos = null;
  private ArrayList<Asignacion_honorarios> asignaciones = null;
  private Asignacion_honorarios asignacion = null;

  /** Creates new form GUIEditarAsignacionHonorarios */
  public GUIEditarAsignacionHonorarios(IServicioProfesoral servicioProfesoral) throws RemoteException {
    initComponents();
    this.setLocationRelativeTo(null);
    this.servicioProfesoral = servicioProfesoral;
    controlConferencista = new ControlConferencista(servicioProfesoral);
    controlPrograma = new ControlPrograma(servicioProfesoral);
    controlAsignaciones = new ControlAsignaciones(servicioProfesoral);
    controlModulo = new ControlModulo(servicioProfesoral);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelAsignarViaticos = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblIcono = new javax.swing.JLabel();
    panelDatosAsignacion = new javax.swing.JPanel();
    lblFechaPago = new javax.swing.JLabel();
    comboFechaPago = new datechooser.beans.DateChooserCombo();
    lblMonto = new javax.swing.JLabel();
    txtMonto = new javax.swing.JTextField();
    btnAsignar = new javax.swing.JButton();
    PanelListadoAsignacion = new javax.swing.JPanel();
    scrollListadoAsignacion = new javax.swing.JScrollPane();
    tableAsignaciones = new javax.swing.JTable();
    panelDatosBusquedaPrograma = new javax.swing.JPanel();
    lblCohorte = new javax.swing.JLabel();
    txtCohorte = new javax.swing.JTextField();
    btnBuscarPrograma = new javax.swing.JButton();
    panelResultadosBusquedaModulo = new javax.swing.JPanel();
    scrollResultados = new javax.swing.JScrollPane();
    tablaResultadosBusqueda = new javax.swing.JTable();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Edicion de Asignacion de Viaticos");

    panelAsignarViaticos.setBackground(new java.awt.Color(255, 255, 255));

    lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
    lblTitulo.setText("Edición de Asignación de Honorarios");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addHonorariosGrande.png"))); // NOI18N

    panelDatosAsignacion.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosAsignacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Asignación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblFechaPago.setFont(new java.awt.Font("Calibri", 2, 13));
    lblFechaPago.setText("Fecha de Pago");

    lblMonto.setFont(new java.awt.Font("Calibri", 2, 13));
    lblMonto.setText("Monto de los Viaticos");

    txtMonto.setFont(new java.awt.Font("Calibri", 2, 13));

    btnAsignar.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    btnAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addHonorarios.png"))); // NOI18N
    btnAsignar.setText("Editar Asignación");
    btnAsignar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAsignarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelDatosAsignacionLayout = new javax.swing.GroupLayout(panelDatosAsignacion);
    panelDatosAsignacion.setLayout(panelDatosAsignacionLayout);
    panelDatosAsignacionLayout.setHorizontalGroup(
      panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblFechaPago)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(comboFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(40, 40, 40)
        .addComponent(lblMonto)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
        .addComponent(btnAsignar)
        .addContainerGap())
    );
    panelDatosAsignacionLayout.setVerticalGroup(
      panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
        .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(comboFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblFechaPago)))
          .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblMonto)
            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAsignar)))
        .addContainerGap(14, Short.MAX_VALUE))
    );

    PanelListadoAsignacion.setBackground(new java.awt.Color(255, 255, 255));
    PanelListadoAsignacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignaciones de viaticos vinculadas al Modulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    tableAsignaciones.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Fecha de Pago", "Monto de la Asignación"
      }
    ));
    tableAsignaciones.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableAsignacionesMouseClicked(evt);
      }
    });
    scrollListadoAsignacion.setViewportView(tableAsignaciones);

    javax.swing.GroupLayout PanelListadoAsignacionLayout = new javax.swing.GroupLayout(PanelListadoAsignacion);
    PanelListadoAsignacion.setLayout(PanelListadoAsignacionLayout);
    PanelListadoAsignacionLayout.setHorizontalGroup(
      PanelListadoAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PanelListadoAsignacionLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollListadoAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        .addContainerGap())
    );
    PanelListadoAsignacionLayout.setVerticalGroup(
      PanelListadoAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListadoAsignacionLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollListadoAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        .addContainerGap())
    );

    panelDatosBusquedaPrograma.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosBusquedaPrograma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda Inicial de Programa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblCohorte.setFont(new java.awt.Font("Calibri", 2, 13));
    lblCohorte.setText("Cohorte del Programa");

    txtCohorte.setFont(new java.awt.Font("Calibri", 2, 13));
    txtCohorte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    btnBuscarPrograma.setFont(new java.awt.Font("Calibri", 3, 13));
    btnBuscarPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarModulo.png"))); // NOI18N
    btnBuscarPrograma.setText("Buscar");
    btnBuscarPrograma.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarProgramaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelDatosBusquedaProgramaLayout = new javax.swing.GroupLayout(panelDatosBusquedaPrograma);
    panelDatosBusquedaPrograma.setLayout(panelDatosBusquedaProgramaLayout);
    panelDatosBusquedaProgramaLayout.setHorizontalGroup(
      panelDatosBusquedaProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosBusquedaProgramaLayout.createSequentialGroup()
        .addGap(113, 113, 113)
        .addComponent(lblCohorte)
        .addGap(21, 21, 21)
        .addComponent(txtCohorte, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnBuscarPrograma)
        .addContainerGap(228, Short.MAX_VALUE))
    );
    panelDatosBusquedaProgramaLayout.setVerticalGroup(
      panelDatosBusquedaProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosBusquedaProgramaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDatosBusquedaProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCohorte)
          .addComponent(btnBuscarPrograma)
          .addComponent(txtCohorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelResultadosBusquedaModulo.setBackground(new java.awt.Color(255, 255, 255));
    panelResultadosBusquedaModulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modulos Vinculados al Programa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    tablaResultadosBusqueda.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Nombre Modulo", "Duración Modulo (Horas)", "Fecha de Inicio", "Valor Hora", "Cohorte Programa", "Cedula Conferencista"
      }
    ));
    tablaResultadosBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaResultadosBusquedaMouseClicked(evt);
      }
    });
    scrollResultados.setViewportView(tablaResultadosBusqueda);

    javax.swing.GroupLayout panelResultadosBusquedaModuloLayout = new javax.swing.GroupLayout(panelResultadosBusquedaModulo);
    panelResultadosBusquedaModulo.setLayout(panelResultadosBusquedaModuloLayout);
    panelResultadosBusquedaModuloLayout.setHorizontalGroup(
      panelResultadosBusquedaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelResultadosBusquedaModuloLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        .addContainerGap())
    );
    panelResultadosBusquedaModuloLayout.setVerticalGroup(
      panelResultadosBusquedaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelResultadosBusquedaModuloLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout panelAsignarViaticosLayout = new javax.swing.GroupLayout(panelAsignarViaticos);
    panelAsignarViaticos.setLayout(panelAsignarViaticosLayout);
    panelAsignarViaticosLayout.setHorizontalGroup(
      panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addComponent(lblTitulo)
            .addGap(18, 18, 18)
            .addComponent(lblIcono))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsignarViaticosLayout.createSequentialGroup()
            .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(PanelListadoAsignacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(panelDatosAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addComponent(panelDatosBusquedaPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())))
      .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(panelResultadosBusquedaModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap()))
    );
    panelAsignarViaticosLayout.setVerticalGroup(
      panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
        .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(lblTitulo))
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblIcono)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelDatosBusquedaPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
        .addComponent(PanelListadoAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelDatosAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
          .addGap(162, 162, 162)
          .addComponent(panelResultadosBusquedaModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(243, Short.MAX_VALUE)))
    );

    menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
    menuArchivo.setText("Archivo");
    menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13));
    barraMenu.add(menuArchivo);

    menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
    menuAyuda.setText("Ayuda");
    menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13));
    barraMenu.add(menuAyuda);

    setJMenuBar(barraMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAsignarViaticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAsignarViaticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
// TODO add your handling code here:
  boolean controlDatos = true;
  double monto = 0;
  Date fechaPago = null;
  if (modulo == null || asignacion == null) {
    JOptionPane.showMessageDialog(rootPane, "Debe buscar modulos por programa, y realizar\nla seleccion del modulo y de la asignación", "Seleccion modulo y asignación", 2);
    controlDatos = false;
  }
  if (txtMonto.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Digitar un valor para el Monto que solo contenga\n"
            + "digitos entre 0 y 9, sin signos ni espacios Ej: 2000", "Error valor Monto Viaticos", 0);
    controlDatos = false;
  } else {
    try {
      monto = Double.parseDouble(txtMonto.getText().trim());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Debe Digitar un valor para el Monto que solo contenga\n"
              + "digitos entre 0 y 9, sin signos ni espacios Ej: 2000", "Error valor Monto Viaticos", 0);
      controlDatos = false;
      System.out.println(e.getMessage());
    }
  }
  if (controlDatos) {
    try {
      fechaPago = formatoFecha.parse(comboFechaPago.getText());
      Asignacion_honorarios asignacionHonorario = new Asignacion_honorarios(asignacion.getId_honorarios(), fechaPago, monto, asignacion.getid_modulo());
      boolean controlAsignacion = controlAsignaciones.EditarAsignacionHonorario(asignacionHonorario);
      if (controlAsignacion) {
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Se ha reaizado la actualizacion de \nlos datos de la Asignación");
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se puede editar la asignación de Honorarios", "Creación fallida", 0);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}//GEN-LAST:event_btnAsignarActionPerformed

private void btnBuscarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProgramaActionPerformed
// TODO add your handling code here:
  String cohorte = "";
  if (txtCohorte.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe digitar una cohorte de Programa para buscar", "Digite cohorte del programa", 0);
  } else {
    cohorte = txtCohorte.getText().trim();
    try {
      modulos = controlModulo.BuscarModuloPrograma(cohorte);
      if (modulos.isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "No se encontraton modulos vinculados al programa", "No hay resultados que mostrar", 0);
        limpiarTablaResultados();
      } else {
        cargarModulos(modulos);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}//GEN-LAST:event_btnBuscarProgramaActionPerformed

private void tablaResultadosBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaResultadosBusquedaMouseClicked
// TODO add your handling code here:
  int fila = tablaResultadosBusqueda.getSelectedRow();
  if (fila != -1) {
    modulo = modulos.get(fila);
    try {
      limpiarAsignaciones();
      asignaciones = controlAsignaciones.BuscarAsignacionHonorario(modulo.getId_modulo());
      cargarAsignaciones();
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}//GEN-LAST:event_tablaResultadosBusquedaMouseClicked

private void tableAsignacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAsignacionesMouseClicked
// TODO add your handling code here:
  int fila = tableAsignaciones.getSelectedRow();
  if (fila != -1) {
    asignacion = asignaciones.get(fila);
    cargarAsignacion();
  }
}//GEN-LAST:event_tableAsignacionesMouseClicked
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel PanelListadoAsignacion;
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JButton btnAsignar;
  private javax.swing.JButton btnBuscarPrograma;
  private datechooser.beans.DateChooserCombo comboFechaPago;
  private javax.swing.JLabel lblCohorte;
  private javax.swing.JLabel lblFechaPago;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JLabel lblMonto;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JPanel panelAsignarViaticos;
  private javax.swing.JPanel panelDatosAsignacion;
  private javax.swing.JPanel panelDatosBusquedaPrograma;
  private javax.swing.JPanel panelResultadosBusquedaModulo;
  private javax.swing.JScrollPane scrollListadoAsignacion;
  private javax.swing.JScrollPane scrollResultados;
  private javax.swing.JTable tablaResultadosBusqueda;
  private javax.swing.JTable tableAsignaciones;
  private javax.swing.JTextField txtCohorte;
  private javax.swing.JTextField txtMonto;
  // End of variables declaration//GEN-END:variables

  private void cargarModulos(ArrayList<Modulo> modulos) {
    int fila = 0;
    for (int i = 0; i < modulos.size(); i++) {
      if (tablaResultadosBusqueda.getRowCount() == fila) {
        DefaultTableModel tablaTemp = (DefaultTableModel) tablaResultadosBusqueda.getModel();
        Object nuevo[] = {null, null, null, null, null, null};
        tablaTemp.addRow(nuevo);
      }
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getNombre_modulo(), i, 0);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getDuracion_modulo_horas(), i, 1);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getFecha_inicio_modulo(), i, 2);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getValor_hora(), i, 3);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getCohorte_programa(), i, 4);
      tablaResultadosBusqueda.setValueAt(modulos.get(i).getCedula_conferencista(), i, 5);
      fila++;
    }
    if (tablaResultadosBusqueda.getRowCount() > fila) {
      DefaultTableModel tablaTemp = (DefaultTableModel) tablaResultadosBusqueda.getModel();
      tablaTemp.removeRow(fila);
    }
  }

  private void limpiarTablaResultados() {
    for (int i = 0; i < tablaResultadosBusqueda.getRowCount(); i++) {
      tablaResultadosBusqueda.setValueAt("", i, 0);
      tablaResultadosBusqueda.setValueAt("", i, 1);
      tablaResultadosBusqueda.setValueAt("", i, 2);
      tablaResultadosBusqueda.setValueAt("", i, 3);
      tablaResultadosBusqueda.setValueAt("", i, 4);
      tablaResultadosBusqueda.setValueAt("", i, 5);
    }
  }

  private void cargarAsignaciones() {
    int fila = 0;
    for (int i = 0; i < asignaciones.size(); i++) {
      if (tableAsignaciones.getRowCount() == fila) {
        DefaultTableModel tablaTemp = (DefaultTableModel) tableAsignaciones.getModel();
        Object nuevo[] = {null, null};
        tablaTemp.addRow(nuevo);
      }
      tableAsignaciones.setValueAt(asignaciones.get(i).getFecha_pago(), i, 0);
      tableAsignaciones.setValueAt(asignaciones.get(i).getMonto_honorarios(), i, 1);
      fila++;
    }
    if (tableAsignaciones.getRowCount() > fila) {
      DefaultTableModel tablaTemp = (DefaultTableModel) tableAsignaciones.getModel();
      tablaTemp.removeRow(fila);
    }
  }

  private void limpiarAsignaciones() {
    txtMonto.setText("");
    for (int i = 0; i < tableAsignaciones.getRowCount(); i++) {
      tableAsignaciones.setValueAt("", i, 0);
      tableAsignaciones.setValueAt("", i, 1);
    }
  }

  private void cargarAsignacion() {
    comboFechaPago.setText(formatoFecha.format(asignacion.getFecha_pago()));
    txtMonto.setText(String.valueOf(asignacion.getMonto_honorarios()));
  }
}
