/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIInformePrograma.java
 *
 * Created on 26/08/2012, 12:07:56 PM
 */
package Vista.Profesoral;

import Controlador.Profesoral.ControlPrograma;
import Estructural.Convenio;
import Estructural.Programa;
import Modelo.IServicioProfesoral;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kmilo
 */
public class GUIInformePrograma extends javax.swing.JFrame {

  private IServicioProfesoral servicioProfesoral;
  private ControlPrograma controlPrograma;
  private DateFormat formatoFecha = new SimpleDateFormat("yyyy");
  private Programa programa;
  private Convenio convenio;
  private GUIEditarPrograma guiEditarPrograma;

  /** Creates new form GUIInformePrograma */
  public GUIInformePrograma(IServicioProfesoral servicioProfesoral, GUIEditarPrograma guiEditarPrograma) {
    initComponents();
    this.servicioProfesoral = servicioProfesoral;
    controlPrograma = new ControlPrograma(servicioProfesoral);
    this.guiEditarPrograma = guiEditarPrograma;
    this.setLocationRelativeTo(null);
    cargarComboAno();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelInformePrograma = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblIcono = new javax.swing.JLabel();
    panelOpcionesBusqueda = new javax.swing.JPanel();
    lblCohorte = new javax.swing.JLabel();
    lblEstado = new javax.swing.JLabel();
    lblSemestre = new javax.swing.JLabel();
    lblAño = new javax.swing.JLabel();
    lblNumeroConvenio = new javax.swing.JLabel();
    txtCohorte = new javax.swing.JTextField();
    txtNumeroConvenio = new javax.swing.JTextField();
    comboEstado = new javax.swing.JComboBox();
    comboSemestre = new javax.swing.JComboBox();
    comboAno = new javax.swing.JComboBox();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Informe de Programas");

    panelInformePrograma.setBackground(new java.awt.Color(255, 255, 255));

    lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
    lblTitulo.setText("Informe de Programas");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informeGrande.png"))); // NOI18N

    panelOpcionesBusqueda.setBackground(new java.awt.Color(255, 255, 255));
    panelOpcionesBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblCohorte.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblCohorte.setText("Cohorte del Programa");

    lblEstado.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblEstado.setText("Estado de Programa");

    lblSemestre.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblSemestre.setText("Semestre");

    lblAño.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblAño.setText("Año");

    lblNumeroConvenio.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblNumeroConvenio.setText("Número Convenio");

    comboEstado.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vendido", "No Vendido" }));
    comboEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    comboSemestre.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    comboSemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Semestre", "Semestre A", "Semestre B" }));

    comboAno.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    comboAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Año" }));

    javax.swing.GroupLayout panelOpcionesBusquedaLayout = new javax.swing.GroupLayout(panelOpcionesBusqueda);
    panelOpcionesBusqueda.setLayout(panelOpcionesBusquedaLayout);
    panelOpcionesBusquedaLayout.setHorizontalGroup(
      panelOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelOpcionesBusquedaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblCohorte)
          .addComponent(lblEstado))
        .addGap(18, 18, 18)
        .addGroup(panelOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(txtCohorte, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(67, 67, 67)
        .addGroup(panelOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelOpcionesBusquedaLayout.createSequentialGroup()
            .addComponent(lblSemestre)
            .addGap(18, 18, 18)
            .addComponent(comboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(35, 35, 35)
            .addComponent(lblAño)
            .addGap(18, 18, 18)
            .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelOpcionesBusquedaLayout.createSequentialGroup()
            .addComponent(lblNumeroConvenio)
            .addGap(18, 18, 18)
            .addComponent(txtNumeroConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(40, Short.MAX_VALUE))
    );
    panelOpcionesBusquedaLayout.setVerticalGroup(
      panelOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelOpcionesBusquedaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCohorte)
          .addComponent(lblSemestre)
          .addComponent(txtCohorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(comboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblAño)
          .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(panelOpcionesBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblEstado)
          .addComponent(lblNumeroConvenio)
          .addComponent(txtNumeroConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(46, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panelInformeProgramaLayout = new javax.swing.GroupLayout(panelInformePrograma);
    panelInformePrograma.setLayout(panelInformeProgramaLayout);
    panelInformeProgramaLayout.setHorizontalGroup(
      panelInformeProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelInformeProgramaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelInformeProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelOpcionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(panelInformeProgramaLayout.createSequentialGroup()
            .addComponent(lblTitulo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblIcono)))
        .addContainerGap(68, Short.MAX_VALUE))
    );
    panelInformeProgramaLayout.setVerticalGroup(
      panelInformeProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelInformeProgramaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelInformeProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblIcono)
          .addGroup(panelInformeProgramaLayout.createSequentialGroup()
            .addGap(8, 8, 8)
            .addComponent(lblTitulo)))
        .addGap(18, 18, 18)
        .addComponent(panelOpcionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(285, Short.MAX_VALUE))
    );

    menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
    menuArchivo.setText("Archivo");
    menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuArchivo);

    menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
    menuAyuda.setText("Ayuda");
    menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    barraMenu.add(menuAyuda);

    setJMenuBar(barraMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelInformePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelInformePrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JComboBox comboAno;
  private javax.swing.JComboBox comboEstado;
  private javax.swing.JComboBox comboSemestre;
  private javax.swing.JLabel lblAño;
  private javax.swing.JLabel lblCohorte;
  private javax.swing.JLabel lblEstado;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JLabel lblNumeroConvenio;
  private javax.swing.JLabel lblSemestre;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JPanel panelInformePrograma;
  private javax.swing.JPanel panelOpcionesBusqueda;
  private javax.swing.JTextField txtCohorte;
  private javax.swing.JTextField txtNumeroConvenio;
  // End of variables declaration//GEN-END:variables

  private void cargarComboAno() {
    Date fecha = new Date();
    int año = 0;
    try {
      String fechaFormato = "";
      fechaFormato = formatoFecha.format(fecha);
      año = Integer.parseInt(fechaFormato);
      for (int i = -20; i < 20; i++) {
        if (i > 0) {
          comboAno.addItem(año + i);
        }else{
          comboAno.addItem(año - i);
        }
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}
