/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIEditarAsignacionViaticos.java
 *
 * Created on 13/11/2012, 01:08:38 PM
 */
package Vista.Profesoral;

import Controlador.Profesoral.ControlAsignaciones;
import Controlador.Profesoral.ControlConferencista;
import Controlador.Profesoral.ControlModulo;
import Controlador.Profesoral.ControlPrograma;
import Estructural.Asignacion_viaticos;
import Estructural.Conferencista;
import Estructural.Modulo;
import Estructural.Programa;
import Modelo.IServicioProfesoral;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Kmilo
 */
public class GUIEditarAsignacionViaticos extends javax.swing.JFrame {
  
  private IServicioProfesoral servicioProfesoral;
  private ControlModulo controlModulo;
  private ControlConferencista controlConferencista;
  private ControlPrograma controlPrograma;
  private ControlAsignaciones controlAsignaciones;
  private Programa programa = null;
  private Conferencista conferencista = null;
  public Modulo modulo;
  private DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");
  private GUIBuscarModulo guiBuscarModulo = null;

  /** Creates new form GUIEditarAsignacionViaticos */
  public GUIEditarAsignacionViaticos(IServicioProfesoral servicioProfesoral, Conferencista conferencista,
          Modulo modulo, GUIBuscarModulo guiBuscarModulo) throws RemoteException {
    initComponents();
    this.setLocationRelativeTo(null);
    this.servicioProfesoral = servicioProfesoral;
    controlConferencista = new ControlConferencista(servicioProfesoral);
    controlPrograma = new ControlPrograma(servicioProfesoral);
    controlAsignaciones = new ControlAsignaciones(servicioProfesoral);
    controlModulo = new ControlModulo(servicioProfesoral);
    this.conferencista = conferencista;
    this.modulo = modulo;
    //deshabilitarCampos();
    cargarModulo();
    this.guiBuscarModulo = guiBuscarModulo;
    if (this.guiBuscarModulo != null) {
      this.guiBuscarModulo.dispose();
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelAsignarViaticos = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblIcono = new javax.swing.JLabel();
    panelDatosModulo = new javax.swing.JPanel();
    lblNombreModulo = new javax.swing.JLabel();
    txtNombreModulo = new javax.swing.JTextField();
    lblDuracionModulo = new javax.swing.JLabel();
    spinDuracion = new javax.swing.JSpinner();
    lblFechaInicio = new javax.swing.JLabel();
    comboFechaInicio = new datechooser.beans.DateChooserCombo();
    lblValor = new javax.swing.JLabel();
    txtValorHora = new javax.swing.JTextField();
    btnBuscarModulo = new javax.swing.JButton();
    panelDatosAsignacion = new javax.swing.JPanel();
    lblFechaPago = new javax.swing.JLabel();
    comboFechaPago = new datechooser.beans.DateChooserCombo();
    lblMonto = new javax.swing.JLabel();
    txtMonto = new javax.swing.JTextField();
    btnAsignar = new javax.swing.JButton();
    PanelListadoAsignacion = new javax.swing.JPanel();
    scrollListadoAsignacion = new javax.swing.JScrollPane();
    tableAsignaciones = new javax.swing.JTable();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Edicion de Asignacion de Viaticos");

    panelAsignarViaticos.setBackground(new java.awt.Color(255, 255, 255));

    lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24));
    lblTitulo.setText("Asignación de Viaticos");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addViaticosGrande .png"))); // NOI18N

    panelDatosModulo.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosModulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Modulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblNombreModulo.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNombreModulo.setText("Nombre");

    txtNombreModulo.setFont(new java.awt.Font("Calibri", 2, 13));
    txtNombreModulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    txtNombreModulo.setEnabled(false);

    lblDuracionModulo.setFont(new java.awt.Font("Calibri", 2, 13));
    lblDuracionModulo.setText("Duración en horas");

    spinDuracion.setFont(new java.awt.Font("Calibri", 2, 13));
    spinDuracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    spinDuracion.setEnabled(false);

    lblFechaInicio.setFont(new java.awt.Font("Calibri", 2, 13));
    lblFechaInicio.setText("Fecha de Inicio");

    lblValor.setFont(new java.awt.Font("Calibri", 2, 13));
    lblValor.setText("Valor Hora");

    txtValorHora.setFont(new java.awt.Font("Calibri", 2, 13));
    txtValorHora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    txtValorHora.setEnabled(false);

    btnBuscarModulo.setFont(new java.awt.Font("Calibri", 3, 13));
    btnBuscarModulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarConvenio.png"))); // NOI18N
    btnBuscarModulo.setText("Buscar Modulo");
    btnBuscarModulo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarModuloActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelDatosModuloLayout = new javax.swing.GroupLayout(panelDatosModulo);
    panelDatosModulo.setLayout(panelDatosModuloLayout);
    panelDatosModuloLayout.setHorizontalGroup(
      panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosModuloLayout.createSequentialGroup()
        .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosModuloLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblNombreModulo)
              .addComponent(lblFechaInicio))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelDatosModuloLayout.createSequentialGroup()
                .addComponent(comboFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValor)
                .addGap(18, 18, 18)
                .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(panelDatosModuloLayout.createSequentialGroup()
                .addComponent(txtNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDuracionModulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(panelDatosModuloLayout.createSequentialGroup()
            .addGap(297, 297, 297)
            .addComponent(btnBuscarModulo)))
        .addContainerGap(106, Short.MAX_VALUE))
    );
    panelDatosModuloLayout.setVerticalGroup(
      panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosModuloLayout.createSequentialGroup()
        .addComponent(btnBuscarModulo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
        .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNombreModulo)
          .addComponent(txtNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblDuracionModulo)
          .addComponent(spinDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblFechaInicio)
          .addGroup(panelDatosModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblValor)
            .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(comboFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    panelDatosAsignacion.setBackground(new java.awt.Color(255, 255, 255));
    panelDatosAsignacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Asignación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    lblFechaPago.setFont(new java.awt.Font("Calibri", 2, 13));
    lblFechaPago.setText("Fecha de Pago");

    lblMonto.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    lblMonto.setText("Monto de los Viaticos");

    txtMonto.setFont(new java.awt.Font("Calibri", 2, 13));

    btnAsignar.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
    btnAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addViatico.png"))); // NOI18N
    btnAsignar.setText("Editar Asignación");
    btnAsignar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAsignarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelDatosAsignacionLayout = new javax.swing.GroupLayout(panelDatosAsignacion);
    panelDatosAsignacion.setLayout(panelDatosAsignacionLayout);
    panelDatosAsignacionLayout.setHorizontalGroup(
      panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblFechaPago)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(comboFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(40, 40, 40)
        .addComponent(lblMonto)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
        .addComponent(btnAsignar)
        .addContainerGap())
    );
    panelDatosAsignacionLayout.setVerticalGroup(
      panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
        .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosAsignacionLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(comboFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblFechaPago)))
          .addGroup(panelDatosAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblMonto)
            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAsignar)))
        .addContainerGap(14, Short.MAX_VALUE))
    );

    PanelListadoAsignacion.setBackground(new java.awt.Color(255, 255, 255));
    PanelListadoAsignacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignaciones vinculadas al Modulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

    tableAsignaciones.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Fecha de Pago", "Monto de la Asignación"
      }
    ));
    scrollListadoAsignacion.setViewportView(tableAsignaciones);

    javax.swing.GroupLayout PanelListadoAsignacionLayout = new javax.swing.GroupLayout(PanelListadoAsignacion);
    PanelListadoAsignacion.setLayout(PanelListadoAsignacionLayout);
    PanelListadoAsignacionLayout.setHorizontalGroup(
      PanelListadoAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PanelListadoAsignacionLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollListadoAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        .addContainerGap())
    );
    PanelListadoAsignacionLayout.setVerticalGroup(
      PanelListadoAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListadoAsignacionLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollListadoAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout panelAsignarViaticosLayout = new javax.swing.GroupLayout(panelAsignarViaticos);
    panelAsignarViaticos.setLayout(panelAsignarViaticosLayout);
    panelAsignarViaticosLayout.setHorizontalGroup(
      panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addComponent(lblTitulo)
            .addGap(18, 18, 18)
            .addComponent(lblIcono))
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addComponent(panelDatosModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsignarViaticosLayout.createSequentialGroup()
            .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(PanelListadoAsignacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(panelDatosAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())))
    );
    panelAsignarViaticosLayout.setVerticalGroup(
      panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
        .addGroup(panelAsignarViaticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(lblTitulo))
          .addGroup(panelAsignarViaticosLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblIcono)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelDatosModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(PanelListadoAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelDatosAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
    menuArchivo.setText("Archivo");
    menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13));
    barraMenu.add(menuArchivo);

    menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
    menuAyuda.setText("Ayuda");
    menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13));
    barraMenu.add(menuAyuda);

    setJMenuBar(barraMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAsignarViaticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelAsignarViaticos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void btnBuscarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModuloActionPerformed
// TODO add your handling code here:
  try {
    GUIBuscarModulo guiBuscarModuloBtn = new GUIBuscarModulo(servicioProfesoral, null, null, null);
    guiBuscarModuloBtn.show();
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
}//GEN-LAST:event_btnBuscarModuloActionPerformed
  
private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
// TODO add your handling code here:
  boolean controlDatos = true;
  double monto = 0;
  Date fechaPago = null;
  if (conferencista == null || modulo == null || programa == null) {
    JOptionPane.showMessageDialog(rootPane, "Debe buscar un conferencista y un modulo\npara Crear la asignación", "Error", 2);
    controlDatos = false;
  }
  if (txtMonto.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Digitar un valor para el Monto que solo contenga\n"
            + "digitos entre 0 y 9, sin signos ni espacios Ej: 2000", "Error valor Monto Viaticos", 0);
    controlDatos = false;
  } else {
    try {
      monto = Double.parseDouble(txtMonto.getText().trim());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Debe Digitar un valor para el Monto que solo contenga\n"
              + "digitos entre 0 y 9, sin signos ni espacios Ej: 2000", "Error valor Monto Viaticos", 0);
      controlDatos = false;
      System.out.println(e.getMessage());
    }
  }
  if (controlDatos) {
    try {
      fechaPago = formatoFecha.parse(comboFechaPago.getText());
      Asignacion_viaticos asignacionViaticos = new Asignacion_viaticos(0, fechaPago, monto, modulo.getId_modulo());
      boolean controlAsignacion = controlAsignaciones.AgregarAsignacionViaticos(asignacionViaticos);
      if (controlAsignacion) {
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Se han asignado los viaticos de manera correcta\n"
                + "¿Desea generar el imprimible de los mismos?", "Asignación creada", 0, 1);
        if (opcion == 0) {
          //Codigo para generar archivo y muestra notificacion
        } else {
          limpiarDatos();
        }
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se puede crear la asignación de viaticos", "Creación fallida", 0);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}//GEN-LAST:event_btnAsignarActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel PanelListadoAsignacion;
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JButton btnAsignar;
  private javax.swing.JButton btnBuscarModulo;
  private datechooser.beans.DateChooserCombo comboFechaInicio;
  private datechooser.beans.DateChooserCombo comboFechaPago;
  private javax.swing.JLabel lblDuracionModulo;
  private javax.swing.JLabel lblFechaInicio;
  private javax.swing.JLabel lblFechaPago;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JLabel lblMonto;
  private javax.swing.JLabel lblNombreModulo;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JLabel lblValor;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JPanel panelAsignarViaticos;
  private javax.swing.JPanel panelDatosAsignacion;
  private javax.swing.JPanel panelDatosModulo;
  private javax.swing.JScrollPane scrollListadoAsignacion;
  private javax.swing.JSpinner spinDuracion;
  private javax.swing.JTable tableAsignaciones;
  private javax.swing.JTextField txtMonto;
  private javax.swing.JTextField txtNombreModulo;
  private javax.swing.JTextField txtValorHora;
  // End of variables declaration//GEN-END:variables

  private void cargarModulo() {
    if (modulo != null) {
      txtNombreModulo.setText(modulo.getNombre_modulo());
      spinDuracion.setValue(modulo.getDuracion_modulo_horas());
      comboFechaInicio.setText(formatoFecha.format(modulo.getFecha_inicio_modulo()));
      txtValorHora.setText(String.valueOf(modulo.getValor_hora()));
      btnBuscarModulo.setEnabled(false);
    }
  }
  
  private void limpiarDatos() {
    txtNombreModulo.setText("");
    txtValorHora.setText("");
    spinDuracion.setValue("");
  }
}
