/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIAdicionAporte.java
 *
 * Created on 21/07/2012, 04:03:19 PM
 */
package Vista;

import Controlador.ControlAporte;
import Estructural.Aportes_convenio;
import Modelo.IServicioConvenios;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Kmilo
 */
public class GUIAdicionAporte extends javax.swing.JFrame {

    private IServicioConvenios servicioConvenios;
    private int numeroConvenio;
    private String NIT;
    private DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");
    private ControlAporte controlAporte;

    /** Creates new form GUIAdicionAporte */
    public GUIAdicionAporte(IServicioConvenios servicioConvenios, String NIT, int numeroConvenio) throws RemoteException {
        initComponents();
        this.servicioConvenios = servicioConvenios;
        this.NIT = NIT;
        this.numeroConvenio = numeroConvenio;
        controlAporte = new ControlAporte(servicioConvenios);
        validarInicio();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosAporte = new javax.swing.JPanel();
        lblAporteConvenio = new javax.swing.JLabel();
        lblLogoAporte = new javax.swing.JLabel();
        panelDatosConvEnti = new javax.swing.JPanel();
        lblNit = new javax.swing.JLabel();
        lblNumeroConvenio = new javax.swing.JLabel();
        lblNitValor = new javax.swing.JLabel();
        lblNumeroConvenioVal = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        comboFechaDesembolso = new datechooser.beans.DateChooserCombo();
        lblFechaDesembolso = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        menuAdicionAporte = new javax.swing.JMenuBar();
        menuArchivoAporte = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        menuAyudaAporte = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicion de aporte");

        panelDatosAporte.setBackground(new java.awt.Color(255, 255, 255));

        lblAporteConvenio.setFont(new java.awt.Font("Calibri", 3, 24));
        lblAporteConvenio.setText("Aporte al convenio");

        lblLogoAporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarAporteGrande.png"))); // NOI18N

        panelDatosConvEnti.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosConvEnti.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Iniciales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N
        panelDatosConvEnti.setFont(new java.awt.Font("Calibri", 2, 13));

        lblNit.setFont(new java.awt.Font("Calibri", 2, 13));
        lblNit.setText("NIT Entidad");

        lblNumeroConvenio.setFont(new java.awt.Font("Calibri", 2, 13));
        lblNumeroConvenio.setText("Número Convenio");

        lblNitValor.setFont(new java.awt.Font("Calibri", 2, 13));
        lblNitValor.setText("NIT Entidad texto");

        lblNumeroConvenioVal.setFont(new java.awt.Font("Calibri", 2, 13));
        lblNumeroConvenioVal.setText("numero Convenio texto");

        lblMonto.setFont(new java.awt.Font("Calibri", 2, 13));
        lblMonto.setText("Monto Aporte");

        lblFechaDesembolso.setFont(new java.awt.Font("Calibri", 2, 13));
        lblFechaDesembolso.setText("Fecha de Desembolso");

        txtMonto.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N

        javax.swing.GroupLayout panelDatosConvEntiLayout = new javax.swing.GroupLayout(panelDatosConvEnti);
        panelDatosConvEnti.setLayout(panelDatosConvEntiLayout);
        panelDatosConvEntiLayout.setHorizontalGroup(
            panelDatosConvEntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosConvEntiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosConvEntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosConvEntiLayout.createSequentialGroup()
                        .addComponent(lblNit)
                        .addGap(30, 30, 30)
                        .addComponent(lblNitValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosConvEntiLayout.createSequentialGroup()
                        .addComponent(lblMonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelDatosConvEntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroConvenio)
                    .addComponent(lblFechaDesembolso))
                .addGap(29, 29, 29)
                .addGroup(panelDatosConvEntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNumeroConvenioVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboFechaDesembolso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelDatosConvEntiLayout.setVerticalGroup(
            panelDatosConvEntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosConvEntiLayout.createSequentialGroup()
                .addGroup(panelDatosConvEntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNit)
                    .addComponent(lblNumeroConvenio)
                    .addComponent(lblNitValor)
                    .addComponent(lblNumeroConvenioVal))
                .addGap(30, 30, 30)
                .addGroup(panelDatosConvEntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosConvEntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMonto)
                        .addComponent(lblFechaDesembolso)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboFechaDesembolso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalir.setFont(new java.awt.Font("Calibri", 3, 13));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Calibri", 3, 13));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadirAporte.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosAporteLayout = new javax.swing.GroupLayout(panelDatosAporte);
        panelDatosAporte.setLayout(panelDatosAporteLayout);
        panelDatosAporteLayout.setHorizontalGroup(
            panelDatosAporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosAporteLayout.createSequentialGroup()
                .addGroup(panelDatosAporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosAporteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAporteConvenio)
                        .addGap(18, 18, 18)
                        .addComponent(lblLogoAporte))
                    .addGroup(panelDatosAporteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosAporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDatosAporteLayout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar))
                            .addComponent(panelDatosConvEnti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelDatosAporteLayout.setVerticalGroup(
            panelDatosAporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosAporteLayout.createSequentialGroup()
                .addGroup(panelDatosAporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosAporteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogoAporte))
                    .addGroup(panelDatosAporteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblAporteConvenio)))
                .addGap(18, 18, 18)
                .addComponent(panelDatosConvEnti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosAporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, 0, 0, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menuArchivoAporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
        menuArchivoAporte.setText("Archivo");
        menuArchivoAporte.setFont(new java.awt.Font("Calibri", 2, 13));

        itemSalir.setFont(new java.awt.Font("Calibri", 2, 13));
        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        itemSalir.setText("Salir");
        menuArchivoAporte.add(itemSalir);

        menuAdicionAporte.add(menuArchivoAporte);

        menuAyudaAporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
        menuAyudaAporte.setText("Ayuda");
        menuAyudaAporte.setFont(new java.awt.Font("Calibri", 2, 13));
        menuAdicionAporte.add(menuAyudaAporte);

        setJMenuBar(menuAdicionAporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosAporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosAporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
// TODO add your handling code here:
    Date fechaDesembolso = null;
    boolean controlDatos = true;
    double montoAporte = 0;
    if (txtMonto.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(rootPane, "Debe Digitar un Monto para el aporte", "Error monto aporte", 0);
        controlDatos = false;
    } else {
        montoAporte = Double.parseDouble(txtMonto.getText().trim());
    }
    if (controlDatos) {
        try {
            fechaDesembolso = formatoFecha.parse(comboFechaDesembolso.getText());
            Aportes_convenio aporte = new Aportes_convenio(0, fechaDesembolso, montoAporte, NIT, numeroConvenio);
            boolean controlAdicion = false;
            controlAdicion = controlAporte.AdicionAporte(aporte);
            if (controlAdicion) {
                JOptionPane.showMessageDialog(rootPane, "Registro de aporte exitoso", "Aporte Registrado", 1);
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se pudo registrar el aporte", "No se pudo registrar el aporte", 2);
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }
}//GEN-LAST:event_btnAgregarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private datechooser.beans.DateChooserCombo comboFechaDesembolso;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JLabel lblAporteConvenio;
    private javax.swing.JLabel lblFechaDesembolso;
    private javax.swing.JLabel lblLogoAporte;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNitValor;
    private javax.swing.JLabel lblNumeroConvenio;
    private javax.swing.JLabel lblNumeroConvenioVal;
    private javax.swing.JMenuBar menuAdicionAporte;
    private javax.swing.JMenu menuArchivoAporte;
    private javax.swing.JMenu menuAyudaAporte;
    private javax.swing.JPanel panelDatosAporte;
    private javax.swing.JPanel panelDatosConvEnti;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

    private void validarInicio() {
        if (numeroConvenio != 0 && !NIT.equals("")) {
            lblNumeroConvenioVal.setText(String.valueOf(numeroConvenio));
            lblNitValor.setText(NIT);
        } else {
            ocultarCampos();
        }
    }

    private void ocultarCampos() {
        lblNumeroConvenioVal.setVisible(false);
        lblNitValor.setVisible(false);
    }
}
