/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIAdicionConvenio.java
 *
 * Created on 10/02/2012, 01:02:03 PM
 */
package Vista;

import Controlador.ControlConvenio;
import Controlador.ControlConvenio_entidad;
import Controlador.ControlEntidad;
import Controlador.ControlPresupuesto;
import Controlador.ControlRubros;
import Estructural.*;
import Modelo.ICambioVista;
import Modelo.IServicioConvenios;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Kmilo
 */
public class GUIAdicionConvenio extends javax.swing.JFrame implements ICambioVista {
  
  private IServicioConvenios servicioConvenios;
  private ControlConvenio controlConvenio;
  private ControlEntidad controlEntidad;
  private ControlConvenio_entidad controlConvenio_entidad;
  private ControlPresupuesto controlPresupuesto;
  private ControlRubros controlRubros;
  private DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");
  private int id_detalle = 0;
  private int numero_convenio = 0;

  /** Creates new form GUIAdicionConvenio */
  public GUIAdicionConvenio(IServicioConvenios servicioConvenios) throws RemoteException {
    initComponents();
    this.servicioConvenios = servicioConvenios;
    controlConvenio = new ControlConvenio(servicioConvenios);
    controlEntidad = new ControlEntidad(servicioConvenios);
    controlConvenio_entidad = new ControlConvenio_entidad(servicioConvenios);
    controlPresupuesto = new ControlPresupuesto(servicioConvenios);
    controlRubros = new ControlRubros(servicioConvenios);
    this.setLocationRelativeTo(null);
    panelPestañasDatos.setEnabledAt(1, false);
    panelPestañasDatos.setEnabledAt(2, false);
    panelEntidades.setEnabled(false);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelGeneral = new javax.swing.JPanel();
    panelNuevoConvenio = new javax.swing.JPanel();
    panelPestañasDatos = new javax.swing.JTabbedPane();
    panelDatosGenerales = new javax.swing.JPanel();
    lblNumeroConvenio = new javax.swing.JLabel();
    txtNumeroConvenio = new javax.swing.JTextField();
    lblFechaInicio = new javax.swing.JLabel();
    comboFechaInicio = new datechooser.beans.DateChooserCombo();
    lblDuracionConvenio = new javax.swing.JLabel();
    spinDuracion = new javax.swing.JSpinner();
    panelObjeto = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtObjeto = new javax.swing.JTextArea();
    btnSiguiente = new javax.swing.JButton();
    lblFechaActa = new javax.swing.JLabel();
    comboFechaActa = new datechooser.beans.DateChooserCombo();
    panelEntidades = new javax.swing.JPanel();
    panelBuscarExistente = new javax.swing.JPanel();
    btn_buscar_entidad = new javax.swing.JButton();
    btn_agregar_entidad = new javax.swing.JButton();
    panelEntidadesAsignadas = new javax.swing.JPanel();
    panelDespEntidades = new javax.swing.JScrollPane();
    tablaEntidades = new javax.swing.JTable();
    btnEliminarEntidadSelecc = new javax.swing.JButton();
    btnAddAporte = new javax.swing.JButton();
    btnSiguienteEntidad = new javax.swing.JButton();
    panelPresupuesto = new javax.swing.JPanel();
    panelDatosBasePresu = new javax.swing.JPanel();
    lblFechaElaboracion = new javax.swing.JLabel();
    comboFechaElaboracion = new datechooser.beans.DateChooserCombo();
    btnAgregarRubro = new javax.swing.JButton();
    panelDatosRubros = new javax.swing.JPanel();
    scrollTablaRubro = new javax.swing.JScrollPane();
    tablaDatosRubros = new javax.swing.JTable();
    btnFinalizarConvenio = new javax.swing.JButton();
    lblTotal = new javax.swing.JLabel();
    lblTotalvalor = new javax.swing.JLabel();
    lblTitulo = new javax.swing.JLabel();
    lblImagen = new javax.swing.JLabel();
    barraMenuConvenio = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    itemSalir = new javax.swing.JMenuItem();
    menuAyuda = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Agregar Nuevo Convenio");
    setFont(new java.awt.Font("Calibri", 0, 14));

    panelGeneral.setBackground(new java.awt.Color(255, 255, 255));

    panelNuevoConvenio.setBackground(new java.awt.Color(255, 255, 255));
    panelNuevoConvenio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Convenio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 14))); // NOI18N

    panelPestañasDatos.setFont(new java.awt.Font("Calibri", 2, 14));

    panelDatosGenerales.setBackground(new java.awt.Color(255, 255, 255));

    lblNumeroConvenio.setFont(new java.awt.Font("Calibri", 2, 13));
    lblNumeroConvenio.setText("Número Convenio");

    txtNumeroConvenio.setFont(new java.awt.Font("Calibri", 0, 12));

    lblFechaInicio.setFont(new java.awt.Font("Calibri", 2, 13));
    lblFechaInicio.setText("Fecha Suscripción Convenio");

    comboFechaInicio.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
      new datechooser.view.appearance.ViewAppearance("custom",
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
          new java.awt.Color(0, 0, 0),
          new java.awt.Color(0, 0, 255),
          false,
          true,
          new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
          new java.awt.Color(0, 0, 0),
          new java.awt.Color(0, 0, 255),
          true,
          true,
          new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
          new java.awt.Color(0, 0, 255),
          new java.awt.Color(0, 0, 255),
          false,
          true,
          new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
          new java.awt.Color(128, 128, 128),
          new java.awt.Color(0, 0, 255),
          false,
          true,
          new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
          new java.awt.Color(0, 0, 0),
          new java.awt.Color(0, 0, 255),
          false,
          true,
          new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
          new java.awt.Color(0, 0, 0),
          new java.awt.Color(255, 0, 0),
          false,
          false,
          new datechooser.view.appearance.swing.ButtonPainter()),
        (datechooser.view.BackRenderer)null,
        false,
        true)));

  lblDuracionConvenio.setFont(new java.awt.Font("Calibri", 2, 13));
  lblDuracionConvenio.setText("Duración Convenio (Días)");

  spinDuracion.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

  panelObjeto.setBackground(new java.awt.Color(255, 255, 255));
  panelObjeto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción del Convenio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

  jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

  txtObjeto.setColumns(20);
  txtObjeto.setLineWrap(true);
  txtObjeto.setRows(5);
  jScrollPane1.setViewportView(txtObjeto);

  javax.swing.GroupLayout panelObjetoLayout = new javax.swing.GroupLayout(panelObjeto);
  panelObjeto.setLayout(panelObjetoLayout);
  panelObjetoLayout.setHorizontalGroup(
    panelObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelObjetoLayout.createSequentialGroup()
      .addContainerGap()
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
      .addContainerGap())
  );
  panelObjetoLayout.setVerticalGroup(
    panelObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelObjetoLayout.createSequentialGroup()
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
      .addContainerGap())
  );

  btnSiguiente.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
  btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siguiente.png"))); // NOI18N
  btnSiguiente.setText("Siguiente");
  btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      btnSiguienteActionPerformed(evt);
    }
  });

  lblFechaActa.setFont(new java.awt.Font("Calibri", 2, 13));
  lblFechaActa.setText("Fecha Acta Inicio");

  comboFechaActa.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
    new datechooser.view.appearance.ViewAppearance("custom",
      new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
        new java.awt.Color(0, 0, 0),
        new java.awt.Color(0, 0, 255),
        false,
        true,
        new datechooser.view.appearance.swing.ButtonPainter()),
      new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
        new java.awt.Color(0, 0, 0),
        new java.awt.Color(0, 0, 255),
        true,
        true,
        new datechooser.view.appearance.swing.ButtonPainter()),
      new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
        new java.awt.Color(0, 0, 255),
        new java.awt.Color(0, 0, 255),
        false,
        true,
        new datechooser.view.appearance.swing.ButtonPainter()),
      new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
        new java.awt.Color(128, 128, 128),
        new java.awt.Color(0, 0, 255),
        false,
        true,
        new datechooser.view.appearance.swing.LabelPainter()),
      new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
        new java.awt.Color(0, 0, 0),
        new java.awt.Color(0, 0, 255),
        false,
        true,
        new datechooser.view.appearance.swing.LabelPainter()),
      new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
        new java.awt.Color(0, 0, 0),
        new java.awt.Color(255, 0, 0),
        false,
        false,
        new datechooser.view.appearance.swing.ButtonPainter()),
      (datechooser.view.BackRenderer)null,
      false,
      true)));

javax.swing.GroupLayout panelDatosGeneralesLayout = new javax.swing.GroupLayout(panelDatosGenerales);
panelDatosGenerales.setLayout(panelDatosGeneralesLayout);
panelDatosGeneralesLayout.setHorizontalGroup(
  panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
  .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
    .addContainerGap(20, Short.MAX_VALUE)
    .addGroup(panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
          .addGroup(panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDuracionConvenio)
            .addComponent(lblNumeroConvenio))
          .addGap(18, 18, 18)
          .addGroup(panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(spinDuracion)
            .addComponent(txtNumeroConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(27, 27, 27)
          .addGroup(panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFechaInicio)
            .addComponent(lblFechaActa))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addGroup(panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(comboFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboFechaActa, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addComponent(panelObjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addComponent(btnSiguiente, javax.swing.GroupLayout.Alignment.TRAILING))
    .addContainerGap())
  );
  panelDatosGeneralesLayout.setVerticalGroup(
    panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
      .addGap(35, 35, 35)
      .addGroup(panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
          .addGroup(panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblNumeroConvenio)
            .addComponent(txtNumeroConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblDuracionConvenio)
            .addComponent(spinDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGroup(panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
            .addComponent(comboFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(comboFechaActa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
            .addComponent(lblFechaInicio)
            .addGap(18, 18, 18)
            .addComponent(lblFechaActa))))
      .addGap(18, 18, 18)
      .addComponent(panelObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(18, 18, 18)
      .addComponent(btnSiguiente)
      .addContainerGap(71, Short.MAX_VALUE))
  );

  panelPestañasDatos.addTab("Datos Generales", panelDatosGenerales);

  panelEntidades.setBackground(new java.awt.Color(255, 255, 255));

  panelBuscarExistente.setBackground(new java.awt.Color(255, 255, 255));
  panelBuscarExistente.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

  btn_buscar_entidad.setFont(new java.awt.Font("Calibri", 3, 13));
  btn_buscar_entidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarConvenio.png"))); // NOI18N
  btn_buscar_entidad.setText("Buscar Entidad Existente");
  btn_buscar_entidad.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      btn_buscar_entidadActionPerformed(evt);
    }
  });

  btn_agregar_entidad.setFont(new java.awt.Font("Calibri", 3, 13));
  btn_agregar_entidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
  btn_agregar_entidad.setText("Agregar Nueva Entidad");
  btn_agregar_entidad.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      btn_agregar_entidadActionPerformed(evt);
    }
  });

  javax.swing.GroupLayout panelBuscarExistenteLayout = new javax.swing.GroupLayout(panelBuscarExistente);
  panelBuscarExistente.setLayout(panelBuscarExistenteLayout);
  panelBuscarExistenteLayout.setHorizontalGroup(
    panelBuscarExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelBuscarExistenteLayout.createSequentialGroup()
      .addGap(142, 142, 142)
      .addComponent(btn_buscar_entidad)
      .addGap(80, 80, 80)
      .addComponent(btn_agregar_entidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGap(197, 197, 197))
  );
  panelBuscarExistenteLayout.setVerticalGroup(
    panelBuscarExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelBuscarExistenteLayout.createSequentialGroup()
      .addGroup(panelBuscarExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
        .addComponent(btn_buscar_entidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btn_agregar_entidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  panelEntidadesAsignadas.setBackground(new java.awt.Color(255, 255, 255));
  panelEntidadesAsignadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidades asignadas a este convenio"));

  tablaEntidades.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {

    },
    new String [] {
      "NIT Entidad", "Nombre Entidad", "Descripción"
    }
  ) {
    boolean[] canEdit = new boolean [] {
      false, true, true
    };

    public boolean isCellEditable(int rowIndex, int columnIndex) {
      return canEdit [columnIndex];
    }
  });
  panelDespEntidades.setViewportView(tablaEntidades);

  btnEliminarEntidadSelecc.setFont(new java.awt.Font("Calibri", 3, 13));
  btnEliminarEntidadSelecc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
  btnEliminarEntidadSelecc.setText("Remover Entidad Seleccionda");
  btnEliminarEntidadSelecc.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      btnEliminarEntidadSeleccActionPerformed(evt);
    }
  });

  btnAddAporte.setFont(new java.awt.Font("Calibri", 3, 13));
  btnAddAporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadirAporte.png"))); // NOI18N
  btnAddAporte.setText("Añadir Aportes de la Entidad seleccionada");
  btnAddAporte.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      btnAddAporteActionPerformed(evt);
    }
  });

  javax.swing.GroupLayout panelEntidadesAsignadasLayout = new javax.swing.GroupLayout(panelEntidadesAsignadas);
  panelEntidadesAsignadas.setLayout(panelEntidadesAsignadasLayout);
  panelEntidadesAsignadasLayout.setHorizontalGroup(
    panelEntidadesAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelEntidadesAsignadasLayout.createSequentialGroup()
      .addContainerGap()
      .addGroup(panelEntidadesAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelDespEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        .addGroup(panelEntidadesAsignadasLayout.createSequentialGroup()
          .addComponent(btnEliminarEntidadSelecc)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
          .addComponent(btnAddAporte)))
      .addContainerGap())
  );
  panelEntidadesAsignadasLayout.setVerticalGroup(
    panelEntidadesAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntidadesAsignadasLayout.createSequentialGroup()
      .addComponent(panelDespEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
      .addGap(18, 18, 18)
      .addGroup(panelEntidadesAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(btnEliminarEntidadSelecc)
        .addComponent(btnAddAporte, 0, 0, Short.MAX_VALUE))
      .addContainerGap())
  );

  btnSiguienteEntidad.setFont(new java.awt.Font("Calibri", 3, 13));
  btnSiguienteEntidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siguiente.png"))); // NOI18N
  btnSiguienteEntidad.setText("Siguiente");
  btnSiguienteEntidad.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      btnSiguienteEntidadActionPerformed(evt);
    }
  });

  javax.swing.GroupLayout panelEntidadesLayout = new javax.swing.GroupLayout(panelEntidades);
  panelEntidades.setLayout(panelEntidadesLayout);
  panelEntidadesLayout.setHorizontalGroup(
    panelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelEntidadesLayout.createSequentialGroup()
      .addContainerGap()
      .addGroup(panelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelEntidadesAsignadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(panelBuscarExistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnSiguienteEntidad, javax.swing.GroupLayout.Alignment.TRAILING))
      .addContainerGap())
  );
  panelEntidadesLayout.setVerticalGroup(
    panelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelEntidadesLayout.createSequentialGroup()
      .addContainerGap()
      .addComponent(panelBuscarExistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(panelEntidadesAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(btnSiguienteEntidad)
      .addContainerGap(39, Short.MAX_VALUE))
  );

  panelPestañasDatos.addTab("Entidades Participantes", panelEntidades);

  panelPresupuesto.setBackground(new java.awt.Color(255, 255, 255));

  panelDatosBasePresu.setBackground(new java.awt.Color(255, 255, 255));
  panelDatosBasePresu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Base del Presupuesto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

  lblFechaElaboracion.setFont(new java.awt.Font("Calibri", 2, 13));
  lblFechaElaboracion.setText("Fecha Elaboración");

  btnAgregarRubro.setFont(new java.awt.Font("Calibri", 3, 13));
  btnAgregarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarRubro.png"))); // NOI18N
  btnAgregarRubro.setText("Agregar nuevo Rubro");
  btnAgregarRubro.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      btnAgregarRubroActionPerformed(evt);
    }
  });

  javax.swing.GroupLayout panelDatosBasePresuLayout = new javax.swing.GroupLayout(panelDatosBasePresu);
  panelDatosBasePresu.setLayout(panelDatosBasePresuLayout);
  panelDatosBasePresuLayout.setHorizontalGroup(
    panelDatosBasePresuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelDatosBasePresuLayout.createSequentialGroup()
      .addContainerGap()
      .addComponent(lblFechaElaboracion)
      .addGap(18, 18, 18)
      .addComponent(comboFechaElaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
      .addComponent(btnAgregarRubro)
      .addGap(64, 64, 64))
  );
  panelDatosBasePresuLayout.setVerticalGroup(
    panelDatosBasePresuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelDatosBasePresuLayout.createSequentialGroup()
      .addGroup(panelDatosBasePresuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(lblFechaElaboracion)
        .addComponent(comboFechaElaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(btnAgregarRubro))
      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  panelDatosRubros.setBackground(new java.awt.Color(255, 255, 255));
  panelDatosRubros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de rubros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 13))); // NOI18N

  tablaDatosRubros.setFont(new java.awt.Font("Calibri", 2, 12));
  tablaDatosRubros.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {

    },
    new String [] {
      "Descripción Rubro", "Cantidad", "Valor Unitario", "Total Rubro"
    }
  ));
  scrollTablaRubro.setViewportView(tablaDatosRubros);

  javax.swing.GroupLayout panelDatosRubrosLayout = new javax.swing.GroupLayout(panelDatosRubros);
  panelDatosRubros.setLayout(panelDatosRubrosLayout);
  panelDatosRubrosLayout.setHorizontalGroup(
    panelDatosRubrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosRubrosLayout.createSequentialGroup()
      .addContainerGap()
      .addComponent(scrollTablaRubro, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
      .addContainerGap())
  );
  panelDatosRubrosLayout.setVerticalGroup(
    panelDatosRubrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelDatosRubrosLayout.createSequentialGroup()
      .addComponent(scrollTablaRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addContainerGap())
  );

  btnFinalizarConvenio.setFont(new java.awt.Font("Calibri", 3, 13));
  btnFinalizarConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/terminar.png"))); // NOI18N
  btnFinalizarConvenio.setText("Finalizar");
  btnFinalizarConvenio.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      btnFinalizarConvenioActionPerformed(evt);
    }
  });

  lblTotal.setFont(new java.awt.Font("Calibri", 2, 13));
  lblTotal.setText("Total Presupuesto (sumatoria de Rubros actuales)");

  lblTotalvalor.setFont(new java.awt.Font("Calibri", 2, 13));
  lblTotalvalor.setText("valor total presupuesto");

  javax.swing.GroupLayout panelPresupuestoLayout = new javax.swing.GroupLayout(panelPresupuesto);
  panelPresupuesto.setLayout(panelPresupuestoLayout);
  panelPresupuestoLayout.setHorizontalGroup(
    panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelPresupuestoLayout.createSequentialGroup()
      .addContainerGap()
      .addGroup(panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelDatosRubros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(panelPresupuestoLayout.createSequentialGroup()
          .addComponent(panelDatosBasePresu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap())
        .addGroup(panelPresupuestoLayout.createSequentialGroup()
          .addGap(10, 10, 10)
          .addComponent(lblTotal)
          .addGap(18, 18, 18)
          .addComponent(lblTotalvalor)
          .addGap(217, 217, 217)
          .addComponent(btnFinalizarConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap())))
  );
  panelPresupuestoLayout.setVerticalGroup(
    panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelPresupuestoLayout.createSequentialGroup()
      .addComponent(panelDatosBasePresu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
      .addComponent(panelDatosRubros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGroup(panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
        .addGroup(panelPresupuestoLayout.createSequentialGroup()
          .addGap(34, 34, 34)
          .addGroup(panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblTotal)
            .addComponent(lblTotalvalor)))
        .addGroup(panelPresupuestoLayout.createSequentialGroup()
          .addGap(18, 18, 18)
          .addComponent(btnFinalizarConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
      .addContainerGap())
  );

  panelPestañasDatos.addTab("Presupuesto", panelPresupuesto);

  javax.swing.GroupLayout panelNuevoConvenioLayout = new javax.swing.GroupLayout(panelNuevoConvenio);
  panelNuevoConvenio.setLayout(panelNuevoConvenioLayout);
  panelNuevoConvenioLayout.setHorizontalGroup(
    panelNuevoConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(panelPestañasDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
  );
  panelNuevoConvenioLayout.setVerticalGroup(
    panelNuevoConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(panelPestañasDatos)
  );

  lblTitulo.setFont(new java.awt.Font("Calibri", 3, 24));
  lblTitulo.setText("Creación de Nuevo Convenio");

  lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConvenioGrande.png"))); // NOI18N

  javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
  panelGeneral.setLayout(panelGeneralLayout);
  panelGeneralLayout.setHorizontalGroup(
    panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelGeneralLayout.createSequentialGroup()
      .addContainerGap()
      .addComponent(lblTitulo)
      .addGap(18, 18, 18)
      .addComponent(lblImagen)
      .addContainerGap(497, Short.MAX_VALUE))
    .addComponent(panelNuevoConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
  );
  panelGeneralLayout.setVerticalGroup(
    panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelGeneralLayout.createSequentialGroup()
      .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelGeneralLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(lblTitulo))
        .addComponent(lblImagen))
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(panelNuevoConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
  menuArchivo.setText("Archivo");
  menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13));

  itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
  itemSalir.setText("Salir");
  itemSalir.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      itemSalirActionPerformed(evt);
    }
  });
  menuArchivo.add(itemSalir);

  barraMenuConvenio.add(menuArchivo);

  menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
  menuAyuda.setText("Ayuda ?");
  menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13));
  barraMenuConvenio.add(menuAyuda);

  setJMenuBar(barraMenuConvenio);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
  );
  layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
  );

  pack();
  }// </editor-fold>//GEN-END:initComponents

private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
// TODO add your handling code here:
  boolean controlDatos = true;
  int numeroConvenio = 0;
  Date fechaInicioConvenio = null;
  Date fechaActaInicio = null;
  int duracionConvenio = 0;
  String objetoConvenio = "";
  if (txtNumeroConvenio.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe Digitar un número de Convenio", "Error número Convenio", 0);
    controlDatos = false;
  } else {
    try {
      numeroConvenio = Integer.parseInt(txtNumeroConvenio.getText().trim());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Debe Digitar un número de Convenio que se\n"
              + "contenga digitos entre 0 y 9 Ej: 0674", "Error número Convenio", 0);
      controlDatos = false;
      System.out.println(e.getMessage());
    }
  }
  if (txtObjeto.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(rootPane, "Debe digitar un objeto para el convenio", "Error Objeto Convenio", 0);
    controlDatos = false;
  } else {
    objetoConvenio = txtObjeto.getText().trim();
  }
  if (controlDatos == true) {
    try {
      boolean controlAdicion = false;
      fechaInicioConvenio = formatoFecha.parse(comboFechaInicio.getText());
      fechaActaInicio = formatoFecha.parse(comboFechaActa.getText());
      duracionConvenio = Integer.parseInt(spinDuracion.getValue().toString());
      Convenio convenio = new Convenio(0, numeroConvenio, fechaInicioConvenio, duracionConvenio, "", "", "", objetoConvenio, "EJECUCION");
      try {
        controlAdicion = controlConvenio.AdicionConvenio(convenio);
        if (controlAdicion == true) {
          JOptionPane.showMessageDialog(rootPane, "Registro inicial Exitoso", "Convenio Registrado", 1);
          Actas acta = new Actas(0, fechaActaInicio, "Acta de Inicio", numeroConvenio);
          controlConvenio.AdicionActa(acta);
          numero_convenio = numeroConvenio;
          limpiarFormulario();
          siguientePestaña();
        } else {
          JOptionPane.showMessageDialog(rootPane, "No se pudo registrar el Convenio", "Error en el Registro", 2);
        }
      } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Problemas con el Servidor", "Problemas de Conexión", 1);
        System.out.println(e.getMessage());
      }
    } catch (ParseException ex) {
      JOptionPane.showMessageDialog(rootPane, "Error en la fecha del Convenio", "Fecha invalida", 0);
      System.out.println(ex.getMessage());
    }
  }
}//GEN-LAST:event_btnSiguienteActionPerformed
  
private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
// TODO add your handling code here:
  this.dispose();
}//GEN-LAST:event_itemSalirActionPerformed
  
private void btn_agregar_entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_entidadActionPerformed
  try {
    GUIAdicionEntidad guiAdicionEntidad = new GUIAdicionEntidad(servicioConvenios, numero_convenio);
    guiAdicionEntidad.show();
  } catch (RemoteException ex) {
    Logger.getLogger(GUIAdicionConvenio.class.getName()).log(Level.SEVERE, null, ex);
  }
}//GEN-LAST:event_btn_agregar_entidadActionPerformed
  
private void btnSiguienteEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteEntidadActionPerformed
// TODO add your handling code here:
  if (tablaEntidades.getRowCount() > 1) {
    agregarColumnas();
    mostrarValoresPresupuesto();
    siguientePestaña();
  } else {
    JOptionPane.showMessageDialog(rootPane, "Debe ingresar al menos dos (2) entidades", "Seleccion de entidades", 2);
  }
}//GEN-LAST:event_btnSiguienteEntidadActionPerformed
  
private void btn_buscar_entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_entidadActionPerformed
// TODO add your handling code here:
  try {
    GUIBuscarEntidad guiBuscarEntidad = new GUIBuscarEntidad(servicioConvenios, numero_convenio);
    guiBuscarEntidad.show();
  } catch (Exception e) {
    System.err.println(e.getMessage());
  }
}//GEN-LAST:event_btn_buscar_entidadActionPerformed
  
private void btnEliminarEntidadSeleccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEntidadSeleccActionPerformed
// TODO add your handling code here:
  int filaSeleccionada = tablaEntidades.getSelectedRow();
  boolean controlEliminacion = false;
  if (filaSeleccionada != -1) {
    String NIT = tablaEntidades.getValueAt(filaSeleccionada, 0).toString().trim();
    int convenio = numero_convenio;
    Convenio_entidad convenio_entidad = new Convenio_entidad(0, convenio, NIT);
    try {
      controlEliminacion = controlConvenio_entidad.EliminarConvenio_entidad(convenio_entidad);
      if (controlEliminacion) {
        JOptionPane.showMessageDialog(rootPane, "Se ha desvinculado la entidad del convenio", "Desvinculacion exitosa", 1);
        tablaEntidades.remove(filaSeleccionada);
      } else {
        JOptionPane.showMessageDialog(rootPane, "No se ha podido desvincular la entidad del convenio", "Error en la desvinculacion", 2);
      }
    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
  } else {
    JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una entidad para eliminar", "Seleccione una entidad", 2);
  }
}//GEN-LAST:event_btnEliminarEntidadSeleccActionPerformed
  
private void btnAddAporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAporteActionPerformed
// TODO add your handling code here:
  int filaSeleccionada = tablaEntidades.getSelectedRow();
  if (filaSeleccionada != -1) {
    String NIT = tablaEntidades.getValueAt(filaSeleccionada, 0).toString().trim();
    int convenio = numero_convenio;
    try {
      GUIAdicionAporte guiAdicionAporte = new GUIAdicionAporte(servicioConvenios, NIT, convenio);
      guiAdicionAporte.show();
    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
  } else {
    JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una entidad", "Seleccione una entidad", 2);
  }
}//GEN-LAST:event_btnAddAporteActionPerformed
  
private void btnAgregarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRubroActionPerformed
// TODO add your handling code here:
  int id_presupuesto = 0;
  Date fecha_presupuesto = null;
  Presupuesto presupuesto = null;
  try {
    presupuesto = controlPresupuesto.PresupuestoPorConvenio(numero_convenio);
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
  if (presupuesto != null) {
    try {
      GUIAdicionRubro guiAdicionRubro = new GUIAdicionRubro(servicioConvenios, numero_convenio);
      guiAdicionRubro.show();
    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
  } else {
    try {
      fecha_presupuesto = formatoFecha.parse(comboFechaElaboracion.getText());
      presupuesto = new Presupuesto(id_presupuesto, fecha_presupuesto, numero_convenio);
      boolean controlAdicion = controlPresupuesto.AdicionPresupuesto(presupuesto);
      if (controlAdicion) {
        GUIAdicionRubro guiAdicionRubro = new GUIAdicionRubro(servicioConvenios, numero_convenio);
        guiAdicionRubro.show();
      } else {
        JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un problema, por favor contacta al administrador", "Falla del sistema", 2);
      }
    } catch (Exception e) {
    }
  }
}//GEN-LAST:event_btnAgregarRubroActionPerformed
  
private void btnFinalizarConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarConvenioActionPerformed
// TODO add your handling code here:
  Presupuesto presupuesto = null;
  ArrayList<Rubro_presupuestal> rubro = null;
  try {
    presupuesto = controlPresupuesto.PresupuestoPorConvenio(numero_convenio);
    rubro = controlRubros.ConsultaRubrosPorPresupuesto(presupuesto);
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
  if (presupuesto != null && rubro != null) {
    JOptionPane.showMessageDialog(rootPane, "Se ha adicionado la información basica del convenio\npara editar elementos o información"
            + "del mismo navegue el menu principal.", "Convenio y componentes regitrados", 1);
    this.dispose();
  } else {
    JOptionPane.showMessageDialog(rootPane, "No se han adicionado Rubros al presupuesto del convenio: " + numero_convenio, "Adicione rubros al presupuesto", 2);
  }
}//GEN-LAST:event_btnFinalizarConvenioActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenuConvenio;
  private javax.swing.JButton btnAddAporte;
  private javax.swing.JButton btnAgregarRubro;
  private javax.swing.JButton btnEliminarEntidadSelecc;
  private javax.swing.JButton btnFinalizarConvenio;
  private javax.swing.JButton btnSiguiente;
  private javax.swing.JButton btnSiguienteEntidad;
  private javax.swing.JButton btn_agregar_entidad;
  private javax.swing.JButton btn_buscar_entidad;
  private datechooser.beans.DateChooserCombo comboFechaActa;
  private datechooser.beans.DateChooserCombo comboFechaElaboracion;
  private datechooser.beans.DateChooserCombo comboFechaInicio;
  private javax.swing.JMenuItem itemSalir;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblDuracionConvenio;
  private javax.swing.JLabel lblFechaActa;
  private javax.swing.JLabel lblFechaElaboracion;
  private javax.swing.JLabel lblFechaInicio;
  private javax.swing.JLabel lblImagen;
  private javax.swing.JLabel lblNumeroConvenio;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JLabel lblTotal;
  private javax.swing.JLabel lblTotalvalor;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JPanel panelBuscarExistente;
  private javax.swing.JPanel panelDatosBasePresu;
  private javax.swing.JPanel panelDatosGenerales;
  private javax.swing.JPanel panelDatosRubros;
  private javax.swing.JScrollPane panelDespEntidades;
  private javax.swing.JPanel panelEntidades;
  private javax.swing.JPanel panelEntidadesAsignadas;
  private javax.swing.JPanel panelGeneral;
  private javax.swing.JPanel panelNuevoConvenio;
  private javax.swing.JPanel panelObjeto;
  private javax.swing.JTabbedPane panelPestañasDatos;
  private javax.swing.JPanel panelPresupuesto;
  private javax.swing.JScrollPane scrollTablaRubro;
  private javax.swing.JSpinner spinDuracion;
  private javax.swing.JTable tablaDatosRubros;
  private javax.swing.JTable tablaEntidades;
  private javax.swing.JTextField txtNumeroConvenio;
  private javax.swing.JTextArea txtObjeto;
  // End of variables declaration//GEN-END:variables

  public void limpiarFormulario() {
    txtNumeroConvenio.setText("");
    txtObjeto.setText("");
    spinDuracion.setValue(1);
  }
  
  private void siguientePestaña() {
    if (panelPestañasDatos.isEnabledAt(0) && !panelPestañasDatos.isEnabledAt(1) && !panelPestañasDatos.isEnabledAt(2)) {
      panelPestañasDatos.setEnabledAt(0, false);
      panelPestañasDatos.setEnabledAt(1, true);
      panelPestañasDatos.setSelectedIndex(1);
    } else if (panelPestañasDatos.isEnabledAt(1) && !panelPestañasDatos.isEnabledAt(0) && !panelPestañasDatos.isEnabledAt(2)) {
      panelPestañasDatos.setEnabledAt(1, false);
      panelPestañasDatos.setEnabledAt(2, true);
      panelPestañasDatos.setSelectedIndex(2);
    } else {
      panelPestañasDatos.setEnabledAt(0, true);
      panelPestañasDatos.setSelectedIndex(0);
      panelPestañasDatos.setEnabledAt(1, false);
      panelPestañasDatos.setEnabledAt(2, false);
    }
  }
  
  public void mostrarEntidades() throws RemoteException {
    ArrayList entidades = new ArrayList<Entidad_convenio>();
    entidades = controlEntidad.ConsultaEntidades(numero_convenio);
    cargarDatosEntidades(entidades);
  }
  
  private void cargarDatosEntidades(ArrayList<Entidad_convenio> entidades) {
    int fila = 0;
    for (int i = 0; i < entidades.size(); i++) {
      if (tablaEntidades.getRowCount() == fila) {
        DefaultTableModel tablaTemp = (DefaultTableModel) tablaEntidades.getModel();
        Object nuevo[] = {null, null, null};
        tablaTemp.addRow(nuevo);
      }
      tablaEntidades.setValueAt(entidades.get(i).getNIT_entidad(), i, 0);
      tablaEntidades.setValueAt(entidades.get(i).getNombre_entidad(), i, 1);
      tablaEntidades.setValueAt(entidades.get(i).getDescripcion_entidad(), i, 2);
      fila++;
    }
    if (tablaEntidades.getRowCount() > fila) {
      DefaultTableModel tablaTemp = (DefaultTableModel) tablaEntidades.getModel();
      tablaTemp.removeRow(fila);
    }
  }
  
  @Override
  public void CambioVista() throws RemoteException {
    mostrarEntidades();
    mostrarValoresPresupuesto();
  }
  
  private void agregarColumnas() {
    //Crando Columnas
    int numeroFilas = tablaEntidades.getRowCount();
    String header = new String();
    for (int i = 0; i < numeroFilas; i++) {
      String nombreEntidad = tablaEntidades.getValueAt(i, 1).toString().trim();
      DefaultTableModel tablaTemp = (DefaultTableModel) tablaDatosRubros.getModel();
      TableColumn columna = new TableColumn();
      header = "Aporte " + nombreEntidad;
      columna.setHeaderValue(header);
      tablaTemp.addColumn(header);
    }
  }
  
  private void mostrarValoresPresupuesto() {
    limpiarDatosPresupuesto();
    Presupuesto presupuesto = null;
    try {
      presupuesto = controlPresupuesto.PresupuestoPorConvenio(numero_convenio);
      if (presupuesto != null) {
        ArrayList<Rubro_presupuestal> rubros = controlRubros.ConsultaRubrosPorPresupuesto(presupuesto);
        if (!rubros.isEmpty()) {
          int numeroColumnas = tablaDatosRubros.getColumnCount();
          int fila = 0;
          for (int i = 0; i < rubros.size(); i++) {
            //Creando filas
            if (tablaDatosRubros.getRowCount() == fila) {
              DefaultTableModel tablaTemp = (DefaultTableModel) tablaDatosRubros.getModel();
              Object nuevo[] = new Object[numeroColumnas];
              tablaTemp.addRow(nuevo);
            }
            ArrayList<Aporte_rubro_entidad> aportesEntidad = controlRubros.ConsultaAportesPorRubroEntidad(rubros.get(i));
            int cantidad = rubros.get(i).getCantidad();
            double valor = rubros.get(i).getValor_unitario();
            double total = cantidad * valor;
            tablaDatosRubros.setValueAt(rubros.get(i).getDescripcion_rubro(), fila, 0);
            tablaDatosRubros.setValueAt(cantidad, fila, 1);
            tablaDatosRubros.setValueAt(valor, fila, 2);
            tablaDatosRubros.setValueAt(total, fila, 3);
            int k = 0;
            if (!aportesEntidad.isEmpty()) {
              for (int j = 4; j < numeroColumnas; j++) {
                tablaDatosRubros.setValueAt(aportesEntidad.get(k).getMonto_aporte_rubro(), fila, j);
                k++;
              }
            }
            fila++;
          }
          if (tablaDatosRubros.getRowCount() > fila) {
            DefaultTableModel tablaTemp = (DefaultTableModel) tablaDatosRubros.getModel();
            tablaTemp.removeRow(fila);
          }
          int numeroFilas = tablaDatosRubros.getRowCount();
          double totalPresupuesto = 0;
          for (int i = 0; i < numeroFilas; i++) {
            totalPresupuesto = totalPresupuesto + Double.parseDouble(tablaDatosRubros.getValueAt(i, 3).toString());
          }
          
          lblTotalvalor.setText(String.valueOf(totalPresupuesto));
        }
      }
    } catch (Exception e) {
    }
  }

  /**
   * Metodo para limpiar la tabla con valores de rubros
   */
  private void limpiarDatosPresupuesto() {
    int columnas = tablaDatosRubros.getColumnCount();
    int filas = tablaDatosRubros.getRowCount();
    for (int i = 0; i < filas; i++) {
      for (int j = 0; j < columnas; j++) {
        tablaDatosRubros.setValueAt("", i, j);
      }
    }
  }
}
