/*
 * Sistema de Información para la toma de Decisiones
 * Centro de Educación Permanente
 * Autor: 
 * Yesid Camilo Ortiz Castillo 
 */

/*
 * GUIAdicionEntidad.java
 *
 * Created on 14/07/2012, 04:38:26 PM
 */
package Vista;

import Controlador.ControlConvenio_entidad;
import Controlador.ControlEntidad;
import Estructural.Convenio_entidad;
import Estructural.Entidad_convenio;
import Modelo.IServicioConvenios;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 *
 * @author Kmilo
 */
public class GUIAdicionEntidad extends javax.swing.JFrame {

    private IServicioConvenios servicioConvenios;
    private int numero_convenio;
    private ControlEntidad controlEntidad;
    private ControlConvenio_entidad controlConvenio_entidad;

    /** Creates new form GUIAdicionEntidad */
    public GUIAdicionEntidad(IServicioConvenios servicioConvenios, int numero_convenio) throws RemoteException {
        initComponents();
        this.numero_convenio = numero_convenio;
        this.servicioConvenios = servicioConvenios;
        controlEntidad = new ControlEntidad(servicioConvenios);
        controlConvenio_entidad = new ControlConvenio_entidad(servicioConvenios);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosEntidad = new javax.swing.JPanel();
        panel_entidad_participante = new javax.swing.JPanel();
        lbl_nit_enti = new javax.swing.JLabel();
        txt_nit_enti = new javax.swing.JTextField();
        lbl_nombre_enti = new javax.swing.JLabel();
        txt_nombre_enti = new javax.swing.JTextField();
        panel_desc_entidad = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_desc_enti = new javax.swing.JTextArea();
        btn_agregar_entidad = new javax.swing.JButton();
        lblTituloEntidad = new javax.swing.JLabel();
        lblLogoEntidad = new javax.swing.JLabel();
        barraMenuEntidad = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar nueva entidad");

        panelDatosEntidad.setBackground(new java.awt.Color(255, 255, 255));

        panel_entidad_participante.setBackground(new java.awt.Color(255, 255, 255));
        panel_entidad_participante.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregue nueva Entidad"));

        lbl_nit_enti.setText("NIT Entidad");

        lbl_nombre_enti.setText("Nombre o Razon Social");

        panel_desc_entidad.setBackground(new java.awt.Color(255, 255, 255));
        panel_desc_entidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción breve de la entidad"));

        txt_desc_enti.setColumns(20);
        txt_desc_enti.setRows(5);
        jScrollPane2.setViewportView(txt_desc_enti);

        javax.swing.GroupLayout panel_desc_entidadLayout = new javax.swing.GroupLayout(panel_desc_entidad);
        panel_desc_entidad.setLayout(panel_desc_entidadLayout);
        panel_desc_entidadLayout.setHorizontalGroup(
            panel_desc_entidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_desc_entidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_desc_entidadLayout.setVerticalGroup(
            panel_desc_entidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_desc_entidadLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_agregar_entidad.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
        btn_agregar_entidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        btn_agregar_entidad.setText("Agregar");
        btn_agregar_entidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_entidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_entidad_participanteLayout = new javax.swing.GroupLayout(panel_entidad_participante);
        panel_entidad_participante.setLayout(panel_entidad_participanteLayout);
        panel_entidad_participanteLayout.setHorizontalGroup(
            panel_entidad_participanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_entidad_participanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_entidad_participanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_desc_entidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_entidad_participanteLayout.createSequentialGroup()
                        .addComponent(lbl_nit_enti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nit_enti, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_nombre_enti)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombre_enti, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_agregar_entidad, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panel_entidad_participanteLayout.setVerticalGroup(
            panel_entidad_participanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_entidad_participanteLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(panel_entidad_participanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nit_enti)
                    .addComponent(txt_nit_enti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre_enti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre_enti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_desc_entidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_agregar_entidad))
        );

        lblTituloEntidad.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        lblTituloEntidad.setText("Nueva Entidad");

        lblLogoEntidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entidad.png"))); // NOI18N

        javax.swing.GroupLayout panelDatosEntidadLayout = new javax.swing.GroupLayout(panelDatosEntidad);
        panelDatosEntidad.setLayout(panelDatosEntidadLayout);
        panelDatosEntidadLayout.setHorizontalGroup(
            panelDatosEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosEntidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosEntidadLayout.createSequentialGroup()
                        .addComponent(lblTituloEntidad)
                        .addGap(28, 28, 28)
                        .addComponent(lblLogoEntidad))
                    .addComponent(panel_entidad_participante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDatosEntidadLayout.setVerticalGroup(
            panelDatosEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosEntidadLayout.createSequentialGroup()
                .addGroup(panelDatosEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosEntidadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloEntidad))
                    .addComponent(lblLogoEntidad))
                .addGap(18, 18, 18)
                .addComponent(panel_entidad_participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuArchivo.png"))); // NOI18N
        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Calibri", 2, 13));

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(itemSalir);

        barraMenuEntidad.add(menuArchivo);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuAyuda.png"))); // NOI18N
        menuAyuda.setText("Ayuda ?");
        menuAyuda.setFont(new java.awt.Font("Calibri", 2, 13));
        barraMenuEntidad.add(menuAyuda);

        setJMenuBar(barraMenuEntidad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_agregar_entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_entidadActionPerformed
// TODO add your handling code here:
    String NIT = "";
    String nombre_enti = "";
    String des_entidad = "";
    boolean controlDatos = true;
    if (txt_nit_enti.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(rootPane, "Debe Digitar un NIT para la entidad", "Error en NIT", 0);
        controlDatos = false;
    } else {
        NIT = txt_nit_enti.getText().trim();
    }
    if (txt_nombre_enti.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(rootPane, "Debe Digitar un Nombre para la entidad", "Nombre invalido", 0);
        controlDatos = false;
    } else {
        nombre_enti = txt_nombre_enti.getText().trim();
    }
    if (txt_desc_enti.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(rootPane, "Debe Digitar una descripción para la entidad", "Descripción invalida", 0);
        controlDatos = false;
    } else {
        des_entidad = txt_desc_enti.getText().trim();
    }
    if (controlDatos == true) {
        Entidad_convenio entidad = new Entidad_convenio(0, NIT, nombre_enti, des_entidad);
        try {
            boolean controlAdicion = controlEntidad.AdicionEntidad(entidad);
            if (controlAdicion) {
                limpiarFormulario();
                JOptionPane.showMessageDialog(rootPane, "Entidad registrada con exito", "Entidad registrada", 1);
                if (numero_convenio != 0) {
                    Convenio_entidad convenio_entidad = new Convenio_entidad(0, numero_convenio, NIT);
                    boolean controlAddRelacion = controlConvenio_entidad.AdicionConvenio_entidad(convenio_entidad);
                    if (controlAddRelacion) {
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Problemas con registros internos", "Contacte el administrador del sistema", 2);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se pudo registrar la entidad \nVerifique los datos", "Error en el Registro", 2);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

}//GEN-LAST:event_btn_agregar_entidadActionPerformed

private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_itemSalirActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenuEntidad;
    private javax.swing.JButton btn_agregar_entidad;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLogoEntidad;
    private javax.swing.JLabel lblTituloEntidad;
    private javax.swing.JLabel lbl_nit_enti;
    private javax.swing.JLabel lbl_nombre_enti;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JPanel panelDatosEntidad;
    private javax.swing.JPanel panel_desc_entidad;
    private javax.swing.JPanel panel_entidad_participante;
    private javax.swing.JTextArea txt_desc_enti;
    private javax.swing.JTextField txt_nit_enti;
    private javax.swing.JTextField txt_nombre_enti;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        txt_desc_enti.setText("");
        txt_nit_enti.setText("");
        txt_nombre_enti.setText("");
    }
}
